"""Initial migration for 'recipe_generator_app'.

Auto-generated by OpenViper on 2026-03-13 21:32:47.
"""

from openviper.db.migrations import executor as migrations

dependencies = []

operations = [
    migrations.CreateTable(
        table_name='recipe_mealplan',
        columns=[
        {'name': 'id', 'type': 'INTEGER', 'nullable': False, 'primary_key': True, 'autoincrement': True},
        {'name': 'user', 'type': 'INTEGER', 'nullable': False},
        {'name': 'title', 'type': 'VARCHAR', 'nullable': False},
        {'name': 'plan_data', 'type': 'TEXT', 'nullable': False},
        {'name': 'week_start', 'type': 'VARCHAR', 'nullable': True},
        {'name': 'created_at', 'type': 'DATETIME', 'nullable': True},
        ],
    ),
    migrations.CreateTable(
        table_name='recipe_nutritioninfo',
        columns=[
        {'name': 'id', 'type': 'INTEGER', 'nullable': False, 'primary_key': True, 'autoincrement': True},
        {'name': 'recipe', 'type': 'INTEGER', 'nullable': False},
        {'name': 'user', 'type': 'INTEGER', 'nullable': False},
        {'name': 'calories', 'type': 'VARCHAR', 'nullable': True},
        {'name': 'protein', 'type': 'VARCHAR', 'nullable': True},
        {'name': 'carbohydrates', 'type': 'VARCHAR', 'nullable': True},
        {'name': 'fat', 'type': 'VARCHAR', 'nullable': True},
        {'name': 'fiber', 'type': 'VARCHAR', 'nullable': True},
        {'name': 'notes', 'type': 'TEXT', 'nullable': True},
        {'name': 'created_at', 'type': 'DATETIME', 'nullable': True},
        ],
    ),
    migrations.CreateTable(
        table_name='recipe_recipe',
        columns=[
        {'name': 'id', 'type': 'INTEGER', 'nullable': False, 'primary_key': True, 'autoincrement': True},
        {'name': 'user', 'type': 'INTEGER', 'nullable': False},
        {'name': 'title', 'type': 'VARCHAR', 'nullable': False},
        {'name': 'ingredients', 'type': 'TEXT', 'nullable': False},
        {'name': 'instructions', 'type': 'TEXT', 'nullable': False},
        {'name': 'servings', 'type': 'VARCHAR', 'nullable': True},
        {'name': 'prep_time', 'type': 'VARCHAR', 'nullable': True},
        {'name': 'cook_time', 'type': 'VARCHAR', 'nullable': True},
        {'name': 'created_at', 'type': 'DATETIME', 'nullable': True},
        ],
    ),
    migrations.CreateTable(
        table_name='recipe_shoppinglist',
        columns=[
        {'name': 'id', 'type': 'INTEGER', 'nullable': False, 'primary_key': True, 'autoincrement': True},
        {'name': 'user', 'type': 'INTEGER', 'nullable': False},
        {'name': 'meal_plan', 'type': 'INTEGER', 'nullable': True},
        {'name': 'items', 'type': 'TEXT', 'nullable': False},
        {'name': 'created_at', 'type': 'DATETIME', 'nullable': True},
        ],
    ),
    migrations.CreateTable(
        table_name='recipe_user_ingredients',
        columns=[
        {'name': 'id', 'type': 'INTEGER', 'nullable': False, 'primary_key': True, 'autoincrement': True},
        {'name': 'user', 'type': 'INTEGER', 'nullable': False},
        {'name': 'ingredients', 'type': 'TEXT', 'nullable': False},
        {'name': 'created_at', 'type': 'DATETIME', 'nullable': True},
        {'name': 'updated_at', 'type': 'DATETIME', 'nullable': True},
        ],
    ),
]
