"""Initial migration for 'users'.

Auto-generated by OpenViper on 2026-06-09 20:11:26.
"""

from openviper.db.migrations import executor as migrations

dependencies = []

operations = [
    migrations.CreateTable(
        table_name="users_user",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "username", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "email", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "password", "type": "VARCHAR", "nullable": True},
            {"name": "first_name", "type": "VARCHAR", "nullable": True},
            {"name": "last_name", "type": "VARCHAR", "nullable": True},
            {"name": "is_active", "type": "BOOLEAN", "nullable": False, "default": True},
            {"name": "is_superuser", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "is_staff", "type": "BOOLEAN", "nullable": False, "default": False},
            {
                "name": "role_profile_id",
                "type": "INTEGER",
                "nullable": True,
                "target_table": "auth_role_profiles",
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
            {"name": "last_login", "type": "DATETIME", "nullable": True},
            {"name": "date_joined", "type": "DATETIME", "nullable": True},
            {"name": "hobby", "type": "VARCHAR", "nullable": True},
            {"name": "photo", "type": "VARCHAR", "nullable": True},
        ],
    ),
    migrations.CreateIndex(
        table_name="users_user",
        index_name="idx_users_user_is_active",
        columns=["is_active"],
    ),
    migrations.CreateIndex(
        table_name="users_user",
        index_name="idx_users_user_is_superuser",
        columns=["is_superuser"],
    ),
    migrations.CreateIndex(
        table_name="users_user",
        index_name="idx_users_user_is_staff",
        columns=["is_staff"],
    ),
    migrations.CreateIndex(
        table_name="users_user",
        index_name="idx_users_user_role_profile_id",
        columns=["role_profile_id"],
    ),
]
