"""Initial migration for users.

Auto-generated by OpenViper on 2026-03-01 15:01:15.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("auth", "0001_initial")]

operations = [
    migrations.CreateTable(
        table_name="users_user",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "username", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "email", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "password", "type": "VARCHAR", "nullable": True},
            {"name": "first_name", "type": "VARCHAR", "nullable": True},
            {"name": "last_name", "type": "VARCHAR", "nullable": True},
            {"name": "is_active", "type": "BOOLEAN", "nullable": False, "default": True},
            {"name": "is_superuser", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "is_staff", "type": "BOOLEAN", "nullable": False, "default": False},
            {
                "name": "role_profile_id",
                "type": "INTEGER",
                "nullable": True,
                "target_table": "auth_role_profiles",
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
            {"name": "last_login", "type": "DATETIME", "nullable": True},
        ],
    ),
]
