"""Migration for users.

Auto-generated by OpenViper on 2026-03-07 10:16:30.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("users", "0001_initial")]

operations = [
    migrations.AddColumn(
        table_name="users_user",
        column_name="hobby",
        column_type="VARCHAR",
    ),
]
