"""Migration for users.

Auto-generated by OpenViper on 2026-03-10 23:07:52.
"""

from openviper.db.migrations import executor as migrations

dependencies = [('users', '0002_add_hobby')]

operations = [
    migrations.AddColumn(
        table_name='users_user',
        column_name='photo',
        column_type='VARCHAR',
    ),
]
