"""Initial migration for 'posts'.

Auto-generated by OpenViper on 2026-06-09 20:11:26.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("users", "0001_initial")]

operations = [
    migrations.CreateTable(
        table_name="posts_post",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "title", "type": "VARCHAR", "nullable": False},
            {"name": "content", "type": "TEXT", "nullable": False},
            {
                "name": "author_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {"name": "is_hidden", "type": "BOOLEAN", "nullable": True, "default": False},
            {"name": "likes_count", "type": "INTEGER", "nullable": True, "default": 0},
            {"name": "comments_count", "type": "INTEGER", "nullable": True, "default": 0},
            {"name": "extra", "type": "JSON", "nullable": True},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="posts_comment",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "post_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "posts_post",
                "on_delete": "CASCADE",
            },
            {"name": "content", "type": "TEXT", "nullable": False},
            {
                "name": "author_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {
                "name": "parent_comment_id",
                "type": "INTEGER",
                "nullable": True,
                "target_table": "posts_comment",
                "on_delete": "CASCADE",
            },
            {"name": "likes_count", "type": "INTEGER", "nullable": True, "default": 0},
            {"name": "is_hidden", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="posts_like",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "post_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "posts_post",
                "on_delete": "CASCADE",
            },
            {
                "name": "user_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="posts_report",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "post_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "posts_post",
                "on_delete": "CASCADE",
            },
            {
                "name": "reported_by_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {"name": "reason", "type": "TEXT", "nullable": False},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="posts_comment_like",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "comment_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "posts_comment",
                "on_delete": "CASCADE",
            },
            {
                "name": "user_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateIndex(
        table_name="posts_post",
        index_name="idx_posts_post_author_id",
        columns=["author_id"],
    ),
    migrations.CreateIndex(
        table_name="posts_comment",
        index_name="idx_posts_comment_post_id",
        columns=["post_id"],
    ),
    migrations.CreateIndex(
        table_name="posts_comment",
        index_name="idx_posts_comment_author_id",
        columns=["author_id"],
    ),
    migrations.CreateIndex(
        table_name="posts_comment",
        index_name="idx_posts_comment_parent_comment_id",
        columns=["parent_comment_id"],
    ),
    migrations.CreateIndex(
        table_name="posts_like",
        index_name="idx_posts_like_post_id",
        columns=["post_id"],
    ),
    migrations.CreateIndex(
        table_name="posts_like",
        index_name="idx_posts_like_user_id",
        columns=["user_id"],
    ),
    migrations.CreateIndex(
        table_name="posts_report",
        index_name="idx_posts_report_post_id",
        columns=["post_id"],
    ),
    migrations.CreateIndex(
        table_name="posts_report",
        index_name="idx_posts_report_reported_by_id",
        columns=["reported_by_id"],
    ),
    migrations.CreateIndex(
        table_name="posts_comment_like",
        index_name="idx_posts_comment_like_comment_id",
        columns=["comment_id"],
    ),
    migrations.CreateIndex(
        table_name="posts_comment_like",
        index_name="idx_posts_comment_like_user_id",
        columns=["user_id"],
    ),
]
