"""Initial migration for posts.

Auto-generated by OpenViper on 2026-03-01 15:01:15.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("users", "0001_initial")]

operations = [
    migrations.CreateTable(
        table_name="posts_post",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "title", "type": "VARCHAR", "nullable": False},
            {"name": "content", "type": "TEXT", "nullable": False},
            {
                "name": "author_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {"name": "is_hidden", "type": "BOOLEAN", "nullable": True, "default": False},
            {"name": "likes_count", "type": "INTEGER", "nullable": True, "default": 0},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="posts_comment",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "post_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "posts_post",
                "on_delete": "CASCADE",
            },
            {"name": "content", "type": "TEXT", "nullable": False},
            {
                "name": "author_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {"name": "is_hidden", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="posts_like",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "post_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "posts_post",
                "on_delete": "CASCADE",
            },
            {
                "name": "user_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="posts_report",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "post_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "posts_post",
                "on_delete": "CASCADE",
            },
            {
                "name": "reported_by_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {"name": "reason", "type": "TEXT", "nullable": False},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
]
