"""Migration for posts.

Auto-generated by OpenViper on 2026-03-10 00:42:26.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("posts", "0001_initial"), ("users", "0002_add_hobby")]

operations = [
    migrations.CreateTable(
        table_name="posts_comment_like",
        columns=[
            {
                "name": "comment_id",
                "type": "INTEGER",
                "field_class": "ForeignKey",
                "nullable": False,
            },
            {
                "name": "created_at",
                "type": "DATETIME",
                "field_class": "DateTimeField",
                "nullable": True,
            },
            {
                "name": "id",
                "type": "INTEGER",
                "field_class": "IntegerField",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "user_id", "type": "INTEGER", "field_class": "ForeignKey", "nullable": False},
        ],
    ),
    migrations.AddColumn(
        table_name="posts_comment",
        column_name="likes_count",
        column_type="INTEGER",
        default=0,
    ),
    migrations.AddColumn(
        table_name="posts_comment",
        column_name="parent_comment_id",
        column_type="INTEGER",
    ),
    migrations.AddColumn(
        table_name="posts_post",
        column_name="comments_count",
        column_type="INTEGER",
        default=0,
    ),
]
