"""Migration for posts.

Auto-generated by OpenViper on 2026-03-11 00:21:29.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("posts", "0002_create_posts_comment_like_add_likes"), ("users", "0003_add_photo")]

operations = [
    migrations.AlterColumn(
        table_name="posts_comment",
        column_name="likes_count",
        column_type="INTEGER",
        nullable=True,
        default=0,
        old_type="INTEGER",
        old_nullable=True,
    ),
    migrations.AddColumn(
        table_name="posts_post",
        column_name="extra",
        column_type="JSON",
        default="{}",
    ),
    migrations.AlterColumn(
        table_name="posts_post",
        column_name="comments_count",
        column_type="INTEGER",
        nullable=True,
        default=0,
        old_type="INTEGER",
        old_nullable=True,
    ),
]
