"""Initial migration for auth.

Auto-generated by OpenViper on 2026-03-01 09:46:04.
"""

from openviper.db.migrations import executor as migrations

dependencies = []

operations = [
    # ── No intra-auth FK dependencies ──────────────────────────────────
    migrations.CreateTable(
        table_name="auth_permissions",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "codename", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "name", "type": "VARCHAR", "nullable": False},
            {"name": "content_type", "type": "VARCHAR", "nullable": True},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="auth_roles",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "name", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "description", "type": "TEXT", "nullable": True},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="auth_role_profiles",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "name", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "description", "type": "TEXT", "nullable": True},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="auth_content_types",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "app_label", "type": "VARCHAR", "nullable": False},
            {"name": "model", "type": "VARCHAR", "nullable": False},
        ],
    ),
    # ── Depend on auth_content_types + auth_roles ───────────────────────
    migrations.CreateTable(
        table_name="auth_content_type_permissions",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "content_type_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_content_types",
                "on_delete": "CASCADE",
            },
            {
                "name": "role_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_roles",
                "on_delete": "CASCADE",
            },
            {"name": "can_create", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "can_read", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "can_update", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "can_delete", "type": "BOOLEAN", "nullable": False, "default": False},
        ],
    ),
    # ── Depend on auth_roles + auth_permissions ─────────────────────────
    migrations.CreateTable(
        table_name="auth_role_permissions",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "role_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_roles",
                "on_delete": "CASCADE",
            },
            {
                "name": "permission_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_permissions",
                "on_delete": "CASCADE",
            },
        ],
    ),
    # ── Depend on auth_role_profiles + auth_roles ───────────────────────
    migrations.CreateTable(
        table_name="auth_role_profile_details",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "role_profile_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_role_profiles",
                "on_delete": "CASCADE",
            },
            {
                "name": "role_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_roles",
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    # ── Depends on auth_role_profiles ───────────────────────────────────
    migrations.CreateTable(
        table_name="auth_users",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "username", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "email", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "password", "type": "VARCHAR", "nullable": True},
            {"name": "first_name", "type": "VARCHAR", "nullable": True},
            {"name": "last_name", "type": "VARCHAR", "nullable": True},
            {"name": "is_active", "type": "BOOLEAN", "nullable": False, "default": True},
            {"name": "is_superuser", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "is_staff", "type": "BOOLEAN", "nullable": False, "default": False},
            {
                "name": "role_profile_id",
                "type": "INTEGER",
                "nullable": True,
                "target_table": "auth_role_profiles",
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
            {"name": "last_login", "type": "DATETIME", "nullable": True},
        ],
    ),
]
