"""Initial migration for auth.

Auto-generated by OpenViper on 2026-03-01 09:46:04.
"""

from openviper.conf import settings as _openviper_settings
from openviper.db.migrations import executor as migrations

_AUTH_USER = "openviper.auth.models.User"


def _resolve_user_table() -> str:
    """Return the configured User model's DB table, falling back to auth_users."""
    user_model_path = getattr(_openviper_settings, "USER_MODEL", None) or getattr(
        _openviper_settings, "AUTH_USER_MODEL", None
    )
    if user_model_path and user_model_path != _AUTH_USER and "." in user_model_path:
        try:
            from importlib import import_module

            module_path, class_name = user_model_path.rsplit(".", 1)
            mod = import_module(module_path)
            cls = getattr(mod, class_name)
            meta = getattr(cls, "Meta", None)
            return getattr(meta, "table_name", "auth_users") if meta else "auth_users"
        except Exception:
            pass
    return "auth_users"


def _resolve_user_dependency() -> list[tuple[str, str]]:
    """Return a dependency on the custom user app's first migration, if applicable."""
    user_model_path = getattr(_openviper_settings, "USER_MODEL", None) or getattr(
        _openviper_settings, "AUTH_USER_MODEL", None
    )
    if user_model_path and user_model_path != _AUTH_USER and "." in user_model_path:
        # Derive app name from the top-level package of the model path.
        # e.g. "users.models.User" -> "users"
        app_name = user_model_path.split(".")[0]
        return [(app_name, "0001_initial")]
    return []


_USER_TABLE = _resolve_user_table()

dependencies = [] + _resolve_user_dependency()


operations = [
    # ── No intra-auth FK dependencies ──────────────────────────────────
    migrations.CreateTable(
        table_name="auth_permissions",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "codename", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "name", "type": "VARCHAR", "nullable": False},
            {"name": "content_type", "type": "VARCHAR", "nullable": True},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="auth_roles",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "name", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "description", "type": "TEXT", "nullable": True},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="auth_role_profiles",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "name", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "description", "type": "TEXT", "nullable": True},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="auth_content_types",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "app_label", "type": "VARCHAR", "nullable": False},
            {"name": "model", "type": "VARCHAR", "nullable": False},
        ],
    ),
    # ── Depend on auth_content_types + auth_roles ───────────────────────
    migrations.CreateTable(
        table_name="auth_content_type_permissions",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "content_type_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_content_types",
                "on_delete": "CASCADE",
            },
            {
                "name": "role_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_roles",
                "on_delete": "CASCADE",
            },
            {"name": "can_create", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "can_read", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "can_update", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "can_delete", "type": "BOOLEAN", "nullable": False, "default": False},
        ],
    ),
    # ── Depend on auth_roles + auth_permissions ─────────────────────────
    migrations.CreateTable(
        table_name="auth_role_permissions",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "role_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_roles",
                "on_delete": "CASCADE",
            },
            {
                "name": "permission_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_permissions",
                "on_delete": "CASCADE",
            },
        ],
    ),
    # ── Depend on auth_role_profiles + auth_roles ───────────────────────
    migrations.CreateTable(
        table_name="auth_role_profile_details",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "role_profile_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_role_profiles",
                "on_delete": "CASCADE",
            },
            {
                "name": "role_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_roles",
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    # ── Depends on auth_role_profiles ───────────────────────────────────
    migrations.CreateTable(
        table_name="auth_users",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "username", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "email", "type": "VARCHAR", "nullable": False, "unique": True},
            {"name": "password", "type": "VARCHAR", "nullable": True},
            {"name": "first_name", "type": "VARCHAR", "nullable": True},
            {"name": "last_name", "type": "VARCHAR", "nullable": True},
            {"name": "is_active", "type": "BOOLEAN", "nullable": False, "default": True},
            {"name": "is_superuser", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "is_staff", "type": "BOOLEAN", "nullable": False, "default": False},
            {
                "name": "role_profile_id",
                "type": "INTEGER",
                "nullable": True,
                "target_table": "auth_role_profiles",
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "updated_at", "type": "DATETIME", "nullable": True},
            {"name": "last_login", "type": "DATETIME", "nullable": True},
            {"name": "date_joined", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="auth_user_roles",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "user_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": _USER_TABLE,
                "on_delete": "CASCADE",
            },
            {
                "name": "role_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "auth_roles",
                "on_delete": "CASCADE",
            },
        ],
    ),
    # ── Depends on auth_users ────────────────────────────────────────────
    migrations.CreateTable(
        table_name="auth_tokens",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {
                "name": "key_hash",
                "type": "VARCHAR",
                "nullable": False,
                "unique": True,
            },
            {
                "name": "user_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": _USER_TABLE,
                "on_delete": "CASCADE",
            },
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "expires_at", "type": "DATETIME", "nullable": True},
            {
                "name": "is_active",
                "type": "BOOLEAN",
                "nullable": False,
                "default": True,
            },
        ],
    ),
]
