"""Migration for 'auth'.

Auto-generated by OpenViper on 2026-06-05 19:51:09.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("auth", "0001_initial")]

operations = [
    migrations.DropTable(table_name="auth_tokens"),
    migrations.CreateIndex(
        table_name="auth_content_type_permissions",
        index_name="idx_auth_content_type_permissions_content_type_id",
        columns=["content_type_id"],
    ),
    migrations.CreateIndex(
        table_name="auth_content_type_permissions",
        index_name="idx_auth_content_type_permissions_role_id",
        columns=["role_id"],
    ),
    migrations.AddColumn(
        table_name="auth_permissions",
        column_name="content_type_id",
        column_type="INTEGER",
    ),
    migrations.RemoveColumn(
        table_name="auth_permissions",
        column_name="content_type",
        column_type="VARCHAR",
    ),
    migrations.CreateIndex(
        table_name="auth_permissions",
        index_name="idx_auth_permissions_content_type_id",
        columns=["content_type_id"],
    ),
    migrations.CreateIndex(
        table_name="auth_role_permissions",
        index_name="idx_auth_role_permissions_permission_id",
        columns=["permission_id"],
    ),
    migrations.CreateIndex(
        table_name="auth_role_permissions",
        index_name="idx_auth_role_permissions_role_id",
        columns=["role_id"],
    ),
    migrations.CreateIndex(
        table_name="auth_role_profile_details",
        index_name="idx_auth_role_profile_details_role_id",
        columns=["role_id"],
    ),
    migrations.CreateIndex(
        table_name="auth_role_profile_details",
        index_name="idx_auth_role_profile_details_role_profile_id",
        columns=["role_profile_id"],
    ),
    migrations.CreateIndex(
        table_name="auth_user_roles",
        index_name="idx_auth_user_roles_role_id",
        columns=["role_id"],
    ),
    migrations.CreateIndex(
        table_name="auth_user_roles",
        index_name="idx_auth_user_roles_user_id",
        columns=["user_id"],
    ),
    migrations.CreateIndex(
        table_name="auth_users",
        index_name="idx_auth_users_is_active",
        columns=["is_active"],
    ),
    migrations.CreateIndex(
        table_name="auth_users",
        index_name="idx_auth_users_is_staff",
        columns=["is_staff"],
    ),
    migrations.CreateIndex(
        table_name="auth_users",
        index_name="idx_auth_users_is_superuser",
        columns=["is_superuser"],
    ),
    migrations.CreateIndex(
        table_name="auth_users",
        index_name="idx_auth_users_role_profile_id",
        columns=["role_profile_id"],
    ),
    migrations.RemoveIndex(table_name="auth_users", index_name="idx_auth_users_email"),
    migrations.RemoveIndex(table_name="auth_users", index_name="idx_auth_users_username"),
]
