"""OpenViper authentication package."""

from __future__ import annotations

import sys

from openviper.utils.importlib import import_string

_LAZY_EXPORTS = {
    "User": ("openviper.auth.models", "User"),
    "AnonymousUser": ("openviper.auth.models", "AnonymousUser"),
    "Role": ("openviper.auth.models", "Role"),
    "Permission": ("openviper.auth.models", "Permission"),
    "UserRole": ("openviper.auth.models", "UserRole"),
    "RolePermission": ("openviper.auth.models", "RolePermission"),
    "make_password": ("openviper.auth.hashers", "make_password"),
    "check_password": ("openviper.auth.hashers", "check_password"),
    "create_access_token": ("openviper.auth.jwt", "create_access_token"),
    "create_refresh_token": ("openviper.auth.jwt", "create_refresh_token"),
    "decode_access_token": ("openviper.auth.jwt", "decode_access_token"),
    "decode_access_token_checked": ("openviper.auth.jwt", "decode_access_token_checked"),
    "decode_refresh_token_checked": ("openviper.auth.jwt", "decode_refresh_token_checked"),
    "decode_token_unverified": ("openviper.auth.jwt", "decode_token_unverified"),
    "authenticate": ("openviper.auth.backends", "authenticate"),
    "login": ("openviper.auth.backends", "login"),
    "logout": ("openviper.auth.backends", "logout"),
    "get_user_by_id": ("openviper.auth.backends", "get_user_by_id"),
    "get_user_model": ("openviper.auth.utils", "get_user_model"),
    "login_required": ("openviper.auth.decorators", "login_required"),
    "permission_required": ("openviper.auth.decorators", "permission_required"),
    "role_required": ("openviper.auth.decorators", "role_required"),
    "superuser_required": ("openviper.auth.decorators", "superuser_required"),
    "staff_required": ("openviper.auth.decorators", "staff_required"),
    "clear_session_cache": ("openviper.auth.sessions", "clear_session_cache"),
    "clear_token_cache": ("openviper.auth.token_blocklist", "clear_token_cache"),
    "TokenAuthentication": ("openviper.auth.authentications", "TokenAuthentication"),
    "create_token": ("openviper.auth.authentications", "create_token"),
    "revoke_auth_token": ("openviper.auth.authentications", "revoke_token"),
    "clear_token_auth_cache": ("openviper.auth.authentications", "clear_token_auth_cache"),
    "create_api_key_credential": ("openviper.auth.authentications", "create_api_key_credential"),
    "create_api_key_pair": ("openviper.auth.authentications", "create_api_key_pair"),
    "reverse_api_key_credential": ("openviper.auth.authentications", "reverse_api_key_credential"),
    "revoke_api_key_pair": ("openviper.auth.authentications", "revoke_api_key_pair"),
    "clear_api_key_cache": ("openviper.auth.authentications", "clear_api_key_cache"),
    "AuthManager": ("openviper.auth.manager", "AuthManager"),
    "JWTBackend": ("openviper.auth.backends.jwt_backend", "JWTBackend"),
    "SessionBackend": ("openviper.auth.backends.session_backend", "SessionBackend"),
    "DatabaseSessionStore": ("openviper.auth.session", "DatabaseSessionStore"),
    "SessionManager": ("openviper.auth.session", "SessionManager"),
    "SessionMiddleware": ("openviper.auth.session", "SessionMiddleware"),
    "BaseLoginView": ("openviper.auth.views.base_login", "BaseLoginView"),
    "JWTLoginView": ("openviper.auth.views.jwt_login", "JWTLoginView"),
    "TokenLoginView": ("openviper.auth.views.token_login", "TokenLoginView"),
    "SessionLoginView": ("openviper.auth.views.session_login", "SessionLoginView"),
    "LogoutView": ("openviper.auth.views.logout", "LogoutView"),
    "MeView": ("openviper.auth.views.me", "MeView"),
    "jwt_routes": ("openviper.auth.views.routes", "jwt_routes"),
    "token_routes": ("openviper.auth.views.routes", "token_routes"),
    "session_routes": ("openviper.auth.views.routes", "session_routes"),
    "all_auth_routes": ("openviper.auth.views.routes", "all_auth_routes"),
    "BaseOAuth2InitView": ("openviper.auth.views.oauth2", "BaseOAuth2InitView"),
    "BaseOAuth2CallbackView": ("openviper.auth.views.oauth2", "BaseOAuth2CallbackView"),
    "GoogleOAuthInitView": ("openviper.auth.views.oauth2", "GoogleOAuthInitView"),
    "GoogleOAuthCallbackView": ("openviper.auth.views.oauth2", "GoogleOAuthCallbackView"),
    "google_oauth_routes": ("openviper.auth.views.oauth2", "google_oauth_routes"),
    "Authenticable": ("openviper.auth.types", "Authenticable"),
    "LoginCredentials": ("openviper.auth.types", "LoginCredentials"),
    "AuthHookConfigError": ("openviper.auth.hooks", "AuthHookConfigError"),
    "AuthHookContext": ("openviper.auth.hooks", "AuthHookContext"),
    "AuthHookError": ("openviper.auth.hooks", "AuthHookError"),
    "AuthHookExecutionError": ("openviper.auth.hooks", "AuthHookExecutionError"),
    "AuthHookReject": ("openviper.auth.hooks", "AuthHookReject"),
    "AuthHookRegistry": ("openviper.auth.hooks", "AuthHookRegistry"),
    "auth_hooks": ("openviper.auth.hooks", "auth_hooks"),
    "register_auth_hook": ("openviper.auth.hooks", "register_auth_hook"),
    "safe_credentials": ("openviper.auth.hooks", "safe_credentials"),
}


def __getattr__(name: str) -> object:
    """Lazily import public authentication exports on first access."""
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    module_path, attr_name = _LAZY_EXPORTS[name]
    value = import_string(f"{module_path}.{attr_name}")
    setattr(sys.modules[__name__], name, value)
    return value


__all__ = [
    "User",
    "AnonymousUser",
    "Role",
    "Permission",
    "UserRole",
    "RolePermission",
    "make_password",
    "check_password",
    "create_access_token",
    "create_refresh_token",
    "decode_access_token",
    "decode_access_token_checked",
    "decode_refresh_token_checked",
    "decode_token_unverified",
    "authenticate",
    "login",
    "logout",
    "get_user_by_id",
    "get_user_model",
    "login_required",
    "permission_required",
    "role_required",
    "superuser_required",
    "staff_required",
    "clear_session_cache",
    "clear_token_cache",
    "TokenAuthentication",
    "create_token",
    "revoke_auth_token",
    "clear_token_auth_cache",
    "create_api_key_credential",
    "create_api_key_pair",
    "reverse_api_key_credential",
    "revoke_api_key_pair",
    "clear_api_key_cache",
    "AuthManager",
    "JWTBackend",
    "SessionBackend",
    "DatabaseSessionStore",
    "SessionManager",
    "SessionMiddleware",
    "BaseLoginView",
    "JWTLoginView",
    "TokenLoginView",
    "SessionLoginView",
    "LogoutView",
    "MeView",
    "jwt_routes",
    "token_routes",
    "session_routes",
    "all_auth_routes",
    "BaseOAuth2InitView",
    "BaseOAuth2CallbackView",
    "GoogleOAuthInitView",
    "GoogleOAuthCallbackView",
    "google_oauth_routes",
    "Authenticable",
    "LoginCredentials",
    "AuthHookConfigError",
    "AuthHookContext",
    "AuthHookError",
    "AuthHookExecutionError",
    "AuthHookReject",
    "AuthHookRegistry",
    "auth_hooks",
    "register_auth_hook",
    "safe_credentials",
]
