"""OpenViper database package."""

from openviper.db import fields
from openviper.db.backends.api import APIVirtualBackend
from openviper.db.backends.base import VirtualBackend, VirtualBackendCapabilities
from openviper.db.backends.database import DatabaseBackend
from openviper.db.backends.db_registry import (
    DatabaseBackendRegistry,
    database_backend_registry,
    get_database_backend_class,
)
from openviper.db.backends.registry import BackendRegistry, backend_registry
from openviper.db.backends.sqlalchemy import DefaultDatabaseBackend
from openviper.db.connection import (
    atomic,
    close_db,
    configure_db,
    get_connection,
    get_engine,
    init_db,
    request_connection,
    transaction,
)
from openviper.db.connections import ConnectionManager, connections
from openviper.db.events import (
    ModelEventDispatcher,
    dispatch_decorator_handlers,
    get_dispatcher,
)
from openviper.db.exceptions import (
    DatabaseAliasNotFoundError,
    DatabaseBackendNotFoundError,
    DatabaseConfigurationError,
    DatabaseOperationNotSupportedError,
    DatabaseReadOnlyError,
    DatabaseRoutingError,
    DatabaseTransactionRoutingError,
    ReadOnlyVirtualModelError,
    SingleModelAlreadyExistsError,
    SingleModelDeleteForbiddenError,
    SingleModelDoesNotExist,
    SingleModelDuplicateForbiddenError,
    SingleModelError,
    UnsupportedVirtualQueryError,
    VirtualBackendNotFoundError,
    VirtualBackendOperationError,
    VirtualModelError,
)
from openviper.db.executor import (
    bypass_permissions,
    escape_like,
    invalidate_query_cache,
    preload_table_schemas,
)
from openviper.db.fields import (
    AutoField,
    BigAutoField,
    BigIntegerField,
    BinaryField,
    BooleanField,
    CharField,
    CheckConstraint,
    Constraint,
    DateField,
    DateTimeField,
    DecimalField,
    DurationField,
    EmailField,
    Field,
    FileField,
    FloatField,
    ForeignKey,
    GenericIPAddressField,
    ImageField,
    IntegerField,
    IPAddressField,
    JSONField,
    LazyFK,
    ManyToManyField,
    NullBooleanField,
    OneToOneField,
    PositiveIntegerField,
    SlugField,
    SmallIntegerField,
    TextField,
    TimeField,
    UniqueConstraint,
    URLField,
    UUIDField,
)
from openviper.db.models import (
    AbstractModel,
    Avg,
    Count,
    F,
    Index,
    Manager,
    Max,
    Min,
    Model,
    ModelOptions,
    Page,
    Q,
    QuerySet,
    Sum,
)
from openviper.db.queryspec import FilterClause, FilterOp, QuerySpec
from openviper.db.routing.admin import AdminRouter
from openviper.db.routing.base import DatabaseRouter
from openviper.db.routing.context import (
    current_db_alias,
    mark_write_used,
    read_from_primary,
    reset_current_alias,
    reset_routing_context,
    set_current_alias,
    write_used,
)
from openviper.db.routing.primary_replica import PrimaryReplicaRouter
from openviper.db.routing.resolver import DefaultRouterResolver, RouterResolver
from openviper.exceptions import TableNotFound

__all__ = [
    # Connection management
    "atomic",
    "close_db",
    "configure_db",
    "get_connection",
    "get_engine",
    "init_db",
    "request_connection",
    "transaction",
    # ORM core
    "AbstractModel",
    "Avg",
    "Count",
    "F",
    "Index",
    "Manager",
    "Max",
    "Min",
    "Model",
    "ModelOptions",
    "Page",
    "Q",
    "QuerySet",
    "Sum",
    # Fields
    "AutoField",
    "BigAutoField",
    "BigIntegerField",
    "BinaryField",
    "BooleanField",
    "CharField",
    "CheckConstraint",
    "Constraint",
    "DateField",
    "DateTimeField",
    "DecimalField",
    "DurationField",
    "EmailField",
    "Field",
    "FileField",
    "FloatField",
    "ForeignKey",
    "GenericIPAddressField",
    "IPAddressField",
    "ImageField",
    "IntegerField",
    "JSONField",
    "LazyFK",
    "ManyToManyField",
    "NullBooleanField",
    "OneToOneField",
    "PositiveIntegerField",
    "SlugField",
    "SmallIntegerField",
    "TextField",
    "TimeField",
    "URLField",
    "UniqueConstraint",
    "UUIDField",
    "fields",
    # Query specification
    "FilterClause",
    "FilterOp",
    "QuerySpec",
    # Executor helpers
    "bypass_permissions",
    "escape_like",
    "invalidate_query_cache",
    "preload_table_schemas",
    # Connections
    "ConnectionManager",
    "connections",
    # Events
    "ModelEventDispatcher",
    "dispatch_decorator_handlers",
    "get_dispatcher",
    # Exceptions
    "DatabaseAliasNotFoundError",
    "DatabaseBackendNotFoundError",
    "DatabaseConfigurationError",
    "DatabaseOperationNotSupportedError",
    "DatabaseReadOnlyError",
    "DatabaseRoutingError",
    "DatabaseTransactionRoutingError",
    "ReadOnlyVirtualModelError",
    "SingleModelAlreadyExistsError",
    "SingleModelDeleteForbiddenError",
    "SingleModelDoesNotExist",
    "SingleModelDuplicateForbiddenError",
    "SingleModelError",
    "TableNotFound",
    "UnsupportedVirtualQueryError",
    "VirtualBackendNotFoundError",
    "VirtualBackendOperationError",
    "VirtualModelError",
    # Virtual backends
    "APIVirtualBackend",
    "BackendRegistry",
    "VirtualBackend",
    "VirtualBackendCapabilities",
    "backend_registry",
    # Database backends
    "DatabaseBackend",
    "DatabaseBackendRegistry",
    "DefaultDatabaseBackend",
    "database_backend_registry",
    "get_database_backend_class",
    # Routing
    "AdminRouter",
    "DatabaseRouter",
    "DefaultRouterResolver",
    "PrimaryReplicaRouter",
    "RouterResolver",
    "current_db_alias",
    "mark_write_used",
    "read_from_primary",
    "reset_current_alias",
    "reset_routing_context",
    "set_current_alias",
    "write_used",
]
