"""Tests for Oracle-specific fixes and recently changed code paths.

Covers:
- patch_oraclejson_serializers staticmethod fix
- Oracle autoincrement with sa.Identity
- FK colspec format (table.column)
- Column case normalization for Oracle
- raw_sql() only/defer with FK field resolution
- raw_sql() with excludes, Q objects, for_update
- SQLGlot-based validate_sql_expression
- wrap_idempotent for Oracle ALTER TABLE
- flush_oracle PL/SQL block handling
"""

from __future__ import annotations

import json
import uuid as uuid_mod
from unittest.mock import MagicMock, patch

import pytest
import sqlalchemy as sa

from openviper.db.connection import get_metadata
from openviper.db.fields import CharField, ForeignKey, IntegerField
from openviper.db.migrations.alembic_sql import DialectSQL
from openviper.db.models import Model, Q, QuerySet

try:
    from sqlalchemy.dialects.oracle.oracledb import (
        OracleDialectAsync_oracledb,
    )
except ImportError:
    OracleDialectAsync_oracledb = None  # type: ignore[assignment]


_ORACLEDB_SKIP_REASON = "oracledb not installed"


class TestOracleJSONSerializers:
    """Verify the staticmethod fix prevents bound-method bug."""

    def test_json_serializer_is_not_bound_method(self) -> None:
        if OracleDialectAsync_oracledb is None:
            pytest.skip(_ORACLEDB_SKIP_REASON)
        OracleDialectAsync_oracledb._json_serializer = staticmethod(
            json.dumps
        )
        d = OracleDialectAsync_oracledb()
        serializer = d._json_serializer
        assert not hasattr(serializer, "__self__")
        result = serializer({"key": "value"})
        assert json.loads(result) == {"key": "value"}

    def test_json_deserializer_is_not_bound_method(self) -> None:
        if OracleDialectAsync_oracledb is None:
            pytest.skip(_ORACLEDB_SKIP_REASON)
        OracleDialectAsync_oracledb._json_deserializer = staticmethod(
            json.loads
        )
        d = OracleDialectAsync_oracledb()
        deserializer = d._json_deserializer
        assert not hasattr(deserializer, "__self__")
        result = deserializer('{"key": "value"}')
        assert result == {"key": "value"}

    def test_plain_function_becomes_bound_method(self) -> None:
        """Verify that without staticmethod, the bug reproduces."""
        if OracleDialectAsync_oracledb is None:
            pytest.skip(_ORACLEDB_SKIP_REASON)
        OracleDialectAsync_oracledb._test_serializer = json.dumps
        d = OracleDialectAsync_oracledb()
        serializer = d._test_serializer
        assert hasattr(serializer, "__self__")
        with pytest.raises(TypeError, match="positional argument"):
            serializer({"key": "value"})
        del OracleDialectAsync_oracledb._test_serializer


class TestOracleAutoincrement:
    """Verify Oracle generates GENERATED BY DEFAULT AS IDENTITY."""

    def test_oracle_autoincrement_uses_identity(self) -> None:
        gen = DialectSQL("oracle")
        stmts = gen.create_table("test_table", [
            {
                "name": "id", "type": "INTEGER",
                "primary_key": True, "autoincrement": True,
                "nullable": False,
            },
            {"name": "name", "type": "VARCHAR(100)", "nullable": False},
        ])
        ddl = stmts[0]
        assert "GENERATED BY DEFAULT AS IDENTITY" in ddl

    def test_oracle_non_autoincrement_no_identity(self) -> None:
        gen = DialectSQL("oracle")
        stmts = gen.create_table("test_table", [
            {
                "name": "id", "type": "INTEGER",
                "primary_key": True, "autoincrement": False,
                "nullable": False,
            },
        ])
        ddl = stmts[0]
        assert "IDENTITY" not in ddl


class TestFKColspecFormat:
    """Verify FK references include column name (table.column)."""

    def test_fk_includes_column_name(self) -> None:
        gen = DialectSQL("postgresql")
        columns = [
            {
                "name": "id", "type": "INTEGER",
                "primary_key": True, "autoincrement": True,
                "nullable": False,
            },
            {
                "name": "author_id", "type": "INTEGER",
                "target_table": "users", "nullable": False,
            },
        ]
        gen.create_table("posts", columns)
        # For non-SQLite vendors, FKs are deferred (ALTER TABLE ADD CONSTRAINT),
        # not inline in CREATE TABLE, to avoid MSSQL cascade-cycle errors.
        fk_stmts = gen.deferred_fk_stmts(
            "posts",
            [{"name": "author_id", "target_table": "users"}],
        )
        ddl = " ".join(fk_stmts)
        assert "users" in ddl
        assert "FOREIGN KEY" in ddl or "REFERENCES" in ddl

    def test_fk_with_custom_target_column(self) -> None:
        # SQLite keeps inline FKs because it cannot ALTER TABLE ADD CONSTRAINT.
        gen = DialectSQL("sqlite")
        col = gen.build_sa_column({
            "name": "parent_id",
            "type": "INTEGER",
            "target_table": "categories",
            "target_column": "uuid",
            "nullable": True,
        })
        fks = list(col.foreign_keys)
        assert len(fks) == 1
        assert "categories.uuid" in str(fks[0])


class TestColumnCaseNormalization:
    """Verify Oracle UPPERCASE column names are handled."""

    def test_case_normalization_lowercases_introspected_cols(self) -> None:
        upper_cols = frozenset({"ID", "NAME", "EMAIL"})
        normalized = frozenset(c.lower() for c in upper_cols)
        table_cols = ["id", "name", "email"]
        result = [c for c in table_cols if c.lower() in normalized]
        assert result == ["id", "name", "email"]

    def test_case_mismatch_produces_empty_without_normalization(self) -> None:
        upper_cols = frozenset({"ID", "NAME"})
        table_cols = ["id", "name"]
        result = [c for c in table_cols if c in upper_cols]
        assert result == []


class TestRawSqlOnlyDefer:
    """Verify raw_sql() handles only/defer with FK field resolution."""

    @pytest.fixture(autouse=True)
    def setup_model(self) -> None:
        suffix = uuid_mod.uuid4().hex[:8]
        author_table = f"test_raw_sql_authors_{suffix}"
        item_table = f"test_raw_sql_items_{suffix}"

        self.metadata = get_metadata()
        self.table = sa.Table(
            item_table, self.metadata,
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("name", sa.String(100)),
            sa.Column("description", sa.Text),
            sa.Column("author_id", sa.Integer,
                      sa.ForeignKey(f"{author_table}.id")),
        )

        class Author(Model):
            name = CharField(max_length=100)

            class Meta:
                table_name = author_table

        class Item(Model):
            name = CharField(max_length=100)
            description = CharField(max_length=500)
            value = IntegerField()
            author = ForeignKey(Author)

            class Meta:
                table_name = item_table

        self.Item = Item
        self.Author = Author

    def test_only_with_fk_field_resolves_to_column(self) -> None:
        qs = QuerySet(self.Item).only("author")
        sql = qs.raw_sql()
        assert "author_id" in sql
        assert "id" in sql

    def test_defer_with_fk_field_resolves_to_column(self) -> None:
        qs = QuerySet(self.Item).defer("author")
        sql = qs.raw_sql()
        assert "author_id" not in sql
        assert "name" in sql


class TestRawSqlFeatures:
    """Verify raw_sql() handles excludes, Q objects, for_update."""

    @pytest.fixture(autouse=True)
    def setup_model(self) -> None:
        self.Q = Q
        suffix = uuid_mod.uuid4().hex[:8]
        tbl = f"test_raw_sql_features_{suffix}"
        self.metadata = get_metadata()
        self.table = sa.Table(
            tbl, self.metadata,
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("name", sa.String(100)),
            sa.Column("status", sa.String(50)),
        )

        class FeatureModel(Model):
            name = CharField(max_length=100)
            status = CharField(max_length=50)

            class Meta:
                table_name = tbl

        self.FeatureModel = FeatureModel

    def test_raw_sql_with_exclude(self) -> None:
        qs = QuerySet(self.FeatureModel).exclude(name="bar")
        sql = qs.raw_sql()
        assert "!=" in sql or "<>" in sql

    def test_raw_sql_with_q_object(self) -> None:
        qs = QuerySet(self.FeatureModel).filter(
            self.Q(name="foo") | self.Q(name="bar")
        )
        sql = qs.raw_sql()
        assert "OR" in sql.upper()

    def test_raw_sql_with_for_update(self) -> None:
        qs = QuerySet(self.FeatureModel).filter(id=1).select_for_update()
        sql = qs.raw_sql()
        assert "FOR UPDATE" in sql.upper()

    def test_raw_sql_with_for_update_nowait(self) -> None:
        qs = QuerySet(self.FeatureModel).filter(id=1).select_for_update(
            nowait=True
        )
        sql = qs.raw_sql()
        assert "FOR UPDATE" in sql.upper()
        assert qs._for_update_nowait is True

    def test_raw_sql_with_for_update_skip_locked(self) -> None:
        qs = QuerySet(self.FeatureModel).filter(id=1).select_for_update(
            skip_locked=True
        )
        sql = qs.raw_sql()
        assert "FOR UPDATE" in sql.upper()
        assert qs._for_update_skip_locked is True

    def test_raw_sql_with_complex_lookup(self) -> None:
        qs = QuerySet(self.FeatureModel).filter(name__icontains="foo")
        sql = qs.raw_sql()
        assert "LIKE" in sql.upper()
        assert ":name_1" in sql


class TestSQLGlotValidation:
    """Verify SQLGlot-based validate_sql_expression."""

    def test_safe_expression_returns_true(self) -> None:
        gen = DialectSQL("postgresql")
        assert gen.validate_sql_expression("price > 0") is True

    def test_drop_table_detected(self) -> None:
        gen = DialectSQL("postgresql")
        assert gen.validate_sql_expression(
            "price > 0; DROP TABLE users"
        ) is False

    def test_delete_detected(self) -> None:
        gen = DialectSQL("postgresql")
        assert gen.validate_sql_expression(
            "1=1; DELETE FROM users WHERE 1=1"
        ) is False

    def test_insert_detected(self) -> None:
        gen = DialectSQL("postgresql")
        assert gen.validate_sql_expression(
            "1=1; INSERT INTO users VALUES (1)"
        ) is False

    def test_update_detected(self) -> None:
        gen = DialectSQL("postgresql")
        assert gen.validate_sql_expression(
            "1=1; UPDATE users SET name='hack'"
        ) is False

    def test_safe_complex_expression(self) -> None:
        gen = DialectSQL("postgresql")
        assert gen.validate_sql_expression(
            "price > 0 AND status IN ('active', 'pending')"
        ) is True


class TestOracleIdempotentWrapping:
    """Verify wrap_idempotent for Oracle ALTER TABLE."""

    def test_alter_table_wrapped_for_oracle(self) -> None:
        gen = DialectSQL("oracle")
        result = gen.wrap_idempotent(
            "ALTER TABLE users ADD COLUMN bio CLOB", "users"
        )
        assert "BEGIN" in result
        assert "EXECUTE IMMEDIATE" in result
        assert "EXCEPTION" in result
        assert "SQLCODE" in result

    def test_create_table_wrapped_for_oracle(self) -> None:
        gen = DialectSQL("oracle")
        result = gen.wrap_idempotent(
            "CREATE TABLE users (id INTEGER)", "users"
        )
        assert "BEGIN" in result
        assert "EXECUTE IMMEDIATE" in result

    def test_drop_table_wrapped_for_oracle(self) -> None:
        gen = DialectSQL("oracle")
        result = gen.wrap_idempotent("DROP TABLE users", "users")
        assert "BEGIN" in result
        assert "EXECUTE IMMEDIATE" in result

    def test_create_index_wrapped_for_oracle(self) -> None:
        gen = DialectSQL("oracle")
        result = gen.wrap_idempotent(
            "CREATE INDEX idx_name ON users (name)", "users"
        )
        assert "BEGIN" in result
        assert "EXECUTE IMMEDIATE" in result

    def test_alter_table_not_wrapped_for_postgresql(self) -> None:
        gen = DialectSQL("postgresql")
        sql = "ALTER TABLE users ADD COLUMN bio TEXT"
        result = gen.wrap_idempotent(sql, "users")
        assert result == sql


class TestOracleFlushPLSQL:
    """Verify flush_oracle preserves PL/SQL blocks."""

    def test_begin_end_block_preserved(self) -> None:
        gen = DialectSQL("oracle")
        gen._buffer.write(
            "BEGIN\n"
            "EXECUTE IMMEDIATE 'CREATE TABLE t (id INTEGER)';\n"
            "EXCEPTION WHEN OTHERS THEN\n"
            "IF SQLCODE != -955 THEN RAISE; END IF;\n"
            "END;\n\n/\n\n"
        )
        result = gen.flush()
        assert len(result) == 1
        assert "BEGIN" in result[0]
        assert "END" in result[0]
        assert "EXECUTE IMMEDIATE" in result[0]
        assert "EXCEPTION" in result[0]

    def test_multiple_statements_split_on_slash(self) -> None:
        gen = DialectSQL("oracle")
        gen._buffer.write(
            "CREATE TABLE a (id INTEGER)\n\n/\n\n"
            "CREATE TABLE b (id INTEGER)\n\n/\n\n"
        )
        result = gen.flush()
        assert len(result) == 2
        assert "CREATE TABLE a" in result[0]
        assert "CREATE TABLE b" in result[1]

    def test_empty_buffer_returns_empty(self) -> None:
        gen = DialectSQL("oracle")
        assert gen.flush() == []

    def test_internal_semicolons_preserved(self) -> None:
        gen = DialectSQL("oracle")
        gen._buffer.write(
            "BEGIN\n"
            "  IF 1 = 1 THEN\n"
            "    EXECUTE IMMEDIATE 'DROP TABLE t';\n"
            "  END IF;\n"
            "EXCEPTION WHEN OTHERS THEN\n"
            "  IF SQLCODE != -942 THEN RAISE; END IF;\n"
            "END;\n\n/\n\n"
        )
        result = gen.flush()
        assert len(result) == 1
        assert ";" in result[0]


class TestMSSQLIdempotentWrapping:
    """Verify wrap_idempotent for MSSQL index operations."""

    def test_create_index_wrapped_with_sys_check(self) -> None:
        gen = DialectSQL("mssql")
        result = gen.wrap_idempotent(
            "CREATE INDEX idx_name ON users (name)", "users"
        )
        assert "IF NOT EXISTS" in result
        assert "sys.indexes" in result

    def test_create_unique_index_wrapped(self) -> None:
        gen = DialectSQL("mssql")
        result = gen.wrap_idempotent(
            "CREATE UNIQUE INDEX uq_email ON users (email)", "users"
        )
        assert "IF NOT EXISTS" in result
        assert "sys.indexes" in result

    def test_drop_index_wrapped_with_sys_check(self) -> None:
        gen = DialectSQL("mssql")
        result = gen.wrap_idempotent(
            "DROP INDEX idx_name ON users", "users"
        )
        assert "IF EXISTS" in result
        assert "sys.indexes" in result

    def test_create_table_wrapped_with_object_id(self) -> None:
        gen = DialectSQL("mssql")
        result = gen.wrap_idempotent(
            "CREATE TABLE [users] (\n  [id] INTEGER NOT NULL,\n  PRIMARY KEY ([id])\n)",
            "users",
        )
        assert "IF OBJECT_ID" in result
        assert "IS NULL" in result

    def test_drop_table_wrapped_with_object_id(self) -> None:
        gen = DialectSQL("mssql")
        result = gen.wrap_idempotent("DROP TABLE [users]", "users")
        assert "IF OBJECT_ID" in result
        assert "IS NOT NULL" in result


class TestDefaultValuesNotStringified:
    """Verify defaults use sql_literal, not str()."""

    def test_boolean_default_not_stringified(self) -> None:
        gen = DialectSQL("postgresql")
        stmts = gen.add_column(
            "users", "active", "BOOLEAN",
            nullable=False, default=True,
        )
        assert "TRUE" in stmts[0]
        assert "'True'" not in stmts[0]

    def test_integer_default_not_stringified(self) -> None:
        gen = DialectSQL("postgresql")
        stmts = gen.add_column(
            "users", "count", "INTEGER",
            nullable=False, default=0,
        )
        assert "DEFAULT 0" in stmts[0]
        assert "'0'" not in stmts[0]

    def test_mssql_boolean_default_uses_one_zero(self) -> None:
        gen = DialectSQL("mssql")
        stmts = gen.add_column(
            "users", "active", "BIT",
            nullable=False, default=True,
        )
        assert "1" in stmts[0]
        assert "TRUE" not in stmts[0]


class TestOracleSQLLiteral:
    """Verify Oracle sql_literal doesn't escape backslashes."""

    def test_oracle_no_backslash_escaping(self) -> None:
        gen = DialectSQL("oracle")
        result = gen.sql_literal("path\\to\\file")
        assert "\\\\" not in result
        assert "path\\to\\file" in result

    def test_mysql_backslash_escaping(self) -> None:
        gen = DialectSQL("mysql")
        result = gen.sql_literal("path\\to\\file")
        assert "\\\\" in result

    def test_oracle_single_quote_escaping(self) -> None:
        gen = DialectSQL("oracle")
        result = gen.sql_literal("it's")
        assert "''" in result


class TestAlterColumnPrimaryKeyUnique:
    """Verify alter_column handles primary_key and unique changes."""

    def test_add_primary_key(self) -> None:
        gen = DialectSQL("postgresql")
        stmts = gen.alter_column(
            "users", "id",
            target_primary_key=True,
        )
        assert any("PRIMARY KEY" in s.upper() for s in stmts)

    def test_drop_primary_key(self) -> None:
        gen = DialectSQL("postgresql")
        stmts = gen.alter_column(
            "users", "id",
            target_primary_key=False,
        )
        assert any("DROP CONSTRAINT" in s.upper() for s in stmts)

    def test_add_unique(self) -> None:
        gen = DialectSQL("postgresql")
        stmts = gen.alter_column(
            "users", "email",
            target_unique=True,
        )
        assert any("UNIQUE" in s.upper() for s in stmts)

    def test_drop_unique(self) -> None:
        gen = DialectSQL("postgresql")
        stmts = gen.alter_column(
            "users", "email",
            target_unique=False,
        )
        assert any("DROP CONSTRAINT" in s.upper() for s in stmts)
