"""Initial migration for 'reviews'.

Auto-generated by OpenViper on 2026-03-14 18:49:34.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("products", "0001_initial"), ("users", "0001_initial")]

operations = [
    migrations.CreateTable(
        table_name="reviews_review",
        columns=[
            {"name": "id", "type": "UUID", "nullable": False, "primary_key": True},
            {
                "name": "user_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {
                "name": "product_id",
                "type": "UUID",
                "nullable": False,
                "target_table": "products_product",
                "on_delete": "CASCADE",
            },
            {"name": "rating", "type": "INTEGER", "nullable": False},
            {"name": "comment", "type": "TEXT", "nullable": True},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
]
