"""Initial migration for 'orders'.

Auto-generated by OpenViper on 2026-03-14 18:49:34.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("products", "0001_initial"), ("users", "0001_initial")]

operations = [
    migrations.CreateTable(
        table_name="orders_order",
        columns=[
            {"name": "id", "type": "UUID", "nullable": False, "primary_key": True},
            {
                "name": "user_id",
                "type": "INTEGER",
                "nullable": False,
                "target_table": "users_user",
                "on_delete": "CASCADE",
            },
            {"name": "total_price", "type": "NUMERIC", "nullable": False, "default": 0},
            {"name": "shipping_address", "type": "TEXT", "nullable": False},
            {"name": "status", "type": "VARCHAR", "nullable": False, "default": "pending"},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="orders_item",
        columns=[
            {"name": "id", "type": "UUID", "nullable": False, "primary_key": True},
            {
                "name": "order_id",
                "type": "UUID",
                "nullable": False,
                "target_table": "orders_order",
                "on_delete": "CASCADE",
            },
            {
                "name": "product_id",
                "type": "UUID",
                "nullable": False,
                "target_table": "products_product",
                "on_delete": "CASCADE",
            },
            {"name": "quantity", "type": "INTEGER", "nullable": False, "default": 1},
            {"name": "price", "type": "NUMERIC", "nullable": False},
        ],
    ),
]
