"""Initial migration for fx.

Auto-generated by OpenViper on 2026-03-06 11:55:56.
"""

from openviper.db.migrations import executor as migrations

dependencies = []

operations = [
    migrations.CreateTable(
        table_name="fx_notes",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "title", "type": "VARCHAR", "nullable": False},
            {"name": "body", "type": "TEXT", "nullable": True},
            {"name": "pinned", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
        ],
    ),
    migrations.CreateTable(
        table_name="fx_tags",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "name", "type": "VARCHAR", "nullable": False},
            {"name": "color", "type": "VARCHAR", "nullable": False, "default": "#3b82f6"},
        ],
    ),
]
