"""Initial migration for todoapp.

Auto-generated by OpenViper on 2026-03-05 19:52:25.
"""

from openviper.db.migrations import executor as migrations

dependencies = []

operations = [
    migrations.CreateTable(
        table_name='miniapp_todos',
        columns=[
        {'name': 'id', 'type': 'INTEGER', 'nullable': False, 'primary_key': True, 'autoincrement': True},
        {'name': 'title', 'type': 'VARCHAR', 'nullable': False},
        {'name': 'done', 'type': 'BOOLEAN', 'nullable': False, 'default': False},
        {'name': 'owner_id', 'type': 'INTEGER', 'nullable': False},
        {'name': 'created_at', 'type': 'DATETIME', 'nullable': True},
        ],
    ),
]
