"""Initial migration for admin.

Auto-generated by OpenViper on 2026-03-01.
"""

from openviper.db.migrations import executor as migrations

dependencies = []

operations = [
    migrations.CreateTable(
        table_name="admin_changehistory",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "model_name", "type": "VARCHAR", "nullable": False},
            {"name": "object_id", "type": "INTEGER", "nullable": False},
            {"name": "object_repr", "type": "VARCHAR", "nullable": False},
            {"name": "action", "type": "VARCHAR", "nullable": False},
            {"name": "changed_fields", "type": "TEXT", "nullable": True},
            {"name": "changed_by_id", "type": "INTEGER", "nullable": True},
            {"name": "changed_by_username", "type": "VARCHAR", "nullable": True},
            {"name": "change_time", "type": "DATETIME", "nullable": True},
            {"name": "change_message", "type": "TEXT", "nullable": True},
        ],
    ),
]
