"""Migration for 'users'.

Auto-generated by OpenViper on 2026-03-29 14:27:11.
"""

from openviper.db.migrations import executor as migrations

dependencies = [("users", "0001_initial")]

operations = [
    migrations.AddColumn(
        table_name="users_user",
        column_name="country",
        column_type="CHAR",
    ),
    migrations.AddColumn(
        table_name="users_user",
        column_name="date_joined",
        column_type="DATETIME",
    ),
]
