"""Initial migration for moderation.

Auto-generated by OpenViper on 2026-02-24 23:05:21.
"""

from openviper.db.migrations import executor as migrations

dependencies = []

operations = [
    migrations.CreateTable(
        table_name="moderation_log",
        columns=[
            {
                "name": "id",
                "type": "INTEGER",
                "nullable": False,
                "primary_key": True,
                "autoincrement": True,
            },
            {"name": "content_type", "type": "VARCHAR", "nullable": False},
            {"name": "object_id", "type": "INTEGER", "nullable": False},
            {"name": "classification", "type": "VARCHAR", "nullable": False},
            {"name": "confidence", "type": "REAL", "nullable": False},
            {"name": "reason", "type": "TEXT", "nullable": False},
            {"name": "reviewed", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "approved", "type": "BOOLEAN", "nullable": False, "default": False},
            {"name": "moderator_id", "type": "INTEGER", "nullable": True},
            {"name": "created_at", "type": "DATETIME", "nullable": True},
            {"name": "reviewed_at", "type": "DATETIME", "nullable": True},
        ],
    ),
]
