"""Pytest utilities for OpenViper applications."""

from openviper.cache.memory import InMemoryCache
from openviper.testing.assertions import (
    assert_cookie,
    assert_error_code,
    assert_field_error,
    assert_field_value,
    assert_header,
    assert_json_contains,
    assert_json_path,
    assert_model_count,
    assert_model_exists,
    assert_queryset_count,
    assert_redirects,
    assert_response_json,
    assert_status,
    assert_validation_error,
)
from openviper.testing.auth import (
    attach_bearer_token,
    attach_session_cookie,
    force_authenticate,
    login_user,
    token_for_user,
    with_permissions,
    with_roles,
)
from openviper.testing.client import OpenViperTestClient
from openviper.testing.database import (
    SessionDatabase,
    TestDatabase,
    migrate_database,
    truncate_database,
)
from openviper.testing.factories import (
    LazyAttribute,
    ModelFactory,
    PermissionFactory,
    PostGeneration,
    RelatedFactory,
    RoleFactory,
    Sequence,
    SuperuserFactory,
    UserFactory,
)
from openviper.testing.fixtures import (
    create_event_recorder,
    create_mailoutbox,
    create_task_queue,
    setup_test_cache,
)
from openviper.testing.settings import (
    DatabaseIsolation,
    OpenViperTestConfig,
    override_openviper_settings,
    override_settings,
)
from openviper.testing.snapshot import Snapshot, assert_matches_snapshot

__all__ = [
    "DatabaseIsolation",
    "InMemoryCache",
    "LazyAttribute",
    "ModelFactory",
    "OpenViperTestClient",
    "OpenViperTestConfig",
    "PermissionFactory",
    "PostGeneration",
    "RelatedFactory",
    "RoleFactory",
    "Sequence",
    "SessionDatabase",
    "SuperuserFactory",
    "UserFactory",
    "Snapshot",
    "TestDatabase",
    "create_event_recorder",
    "create_mailoutbox",
    "create_task_queue",
    "setup_test_cache",
    "assert_error_code",
    "assert_field_error",
    "assert_field_value",
    "assert_cookie",
    "assert_header",
    "assert_json_contains",
    "assert_json_path",
    "assert_matches_snapshot",
    "assert_model_count",
    "assert_model_exists",
    "assert_queryset_count",
    "assert_redirects",
    "assert_response_json",
    "assert_status",
    "assert_validation_error",
    "attach_bearer_token",
    "attach_session_cookie",
    "force_authenticate",
    "login_user",
    "migrate_database",
    "override_openviper_settings",
    "override_settings",
    "token_for_user",
    "truncate_database",
    "with_permissions",
    "with_roles",
]
