"""ISO 3166-1 alpha-2 country dataset.

Immutable in-memory country registry. No database, no external API.
Data is a plain dict keyed by ISO alpha-2 code for O(1) lookup.

Two dicts are provided:

``COUNTRIES``
    Lightweight core data (name + dial_code) used by validation and
    choice generation — kept minimal so startup cost stays negligible.

``COUNTRY_META``
    Richer per-country metadata (alpha3, numeric, continent, region,
    capital, currency_code, currency_name, languages, tld, is_eu,
    is_eea, timezone).  Sourced from ISO 3166-1, UN M.49, and IANA.
    Accessed lazily through ``cache.get_country_meta()``.
"""

from __future__ import annotations

from typing import Final, TypedDict


class CountryInfo(TypedDict):
    """Lightweight core country entry (name + dial_code)."""

    name: str
    dial_code: str


class CountryMeta(TypedDict):
    """Extended country metadata for property access on Country instances."""

    alpha3: str
    numeric: str
    continent: str
    region: str
    capital: str
    currency_code: str
    currency_name: str
    currency_symbol: str
    languages: list[str]
    tld: str
    is_eu: bool
    is_eea: bool
    timezone: str


COUNTRIES: Final[dict[str, CountryInfo]] = {
    "AD": {"name": "Andorra", "dial_code": "+376"},
    "AE": {"name": "United Arab Emirates", "dial_code": "+971"},
    "AF": {"name": "Afghanistan", "dial_code": "+93"},
    "AG": {"name": "Antigua and Barbuda", "dial_code": "+1-268"},
    "AI": {"name": "Anguilla", "dial_code": "+1-264"},
    "AL": {"name": "Albania", "dial_code": "+355"},
    "AM": {"name": "Armenia", "dial_code": "+374"},
    "AO": {"name": "Angola", "dial_code": "+244"},
    "AQ": {"name": "Antarctica", "dial_code": "+672"},
    "AR": {"name": "Argentina", "dial_code": "+54"},
    "AS": {"name": "American Samoa", "dial_code": "+1-684"},
    "AT": {"name": "Austria", "dial_code": "+43"},
    "AU": {"name": "Australia", "dial_code": "+61"},
    "AW": {"name": "Aruba", "dial_code": "+297"},
    "AX": {"name": "Aland Islands", "dial_code": "+358"},
    "AZ": {"name": "Azerbaijan", "dial_code": "+994"},
    "BA": {"name": "Bosnia and Herzegovina", "dial_code": "+387"},
    "BB": {"name": "Barbados", "dial_code": "+1-246"},
    "BD": {"name": "Bangladesh", "dial_code": "+880"},
    "BE": {"name": "Belgium", "dial_code": "+32"},
    "BF": {"name": "Burkina Faso", "dial_code": "+226"},
    "BG": {"name": "Bulgaria", "dial_code": "+359"},
    "BH": {"name": "Bahrain", "dial_code": "+973"},
    "BI": {"name": "Burundi", "dial_code": "+257"},
    "BJ": {"name": "Benin", "dial_code": "+229"},
    "BL": {"name": "Saint Barthelemy", "dial_code": "+590"},
    "BM": {"name": "Bermuda", "dial_code": "+1-441"},
    "BN": {"name": "Brunei", "dial_code": "+673"},
    "BO": {"name": "Bolivia", "dial_code": "+591"},
    "BQ": {"name": "Bonaire, Saint Eustatius and Saba", "dial_code": "+599"},
    "BR": {"name": "Brazil", "dial_code": "+55"},
    "BS": {"name": "Bahamas", "dial_code": "+1-242"},
    "BT": {"name": "Bhutan", "dial_code": "+975"},
    "BV": {"name": "Bouvet Island", "dial_code": "+47"},
    "BW": {"name": "Botswana", "dial_code": "+267"},
    "BY": {"name": "Belarus", "dial_code": "+375"},
    "BZ": {"name": "Belize", "dial_code": "+501"},
    "CA": {"name": "Canada", "dial_code": "+1"},
    "CC": {"name": "Cocos Islands", "dial_code": "+61"},
    "CD": {"name": "Democratic Republic of the Congo", "dial_code": "+243"},
    "CF": {"name": "Central African Republic", "dial_code": "+236"},
    "CG": {"name": "Republic of the Congo", "dial_code": "+242"},
    "CH": {"name": "Switzerland", "dial_code": "+41"},
    "CI": {"name": "Ivory Coast", "dial_code": "+225"},
    "CK": {"name": "Cook Islands", "dial_code": "+682"},
    "CL": {"name": "Chile", "dial_code": "+56"},
    "CM": {"name": "Cameroon", "dial_code": "+237"},
    "CN": {"name": "China", "dial_code": "+86"},
    "CO": {"name": "Colombia", "dial_code": "+57"},
    "CR": {"name": "Costa Rica", "dial_code": "+506"},
    "CU": {"name": "Cuba", "dial_code": "+53"},
    "CV": {"name": "Cape Verde", "dial_code": "+238"},
    "CW": {"name": "Curacao", "dial_code": "+599"},
    "CX": {"name": "Christmas Island", "dial_code": "+61"},
    "CY": {"name": "Cyprus", "dial_code": "+357"},
    "CZ": {"name": "Czech Republic", "dial_code": "+420"},
    "DE": {"name": "Germany", "dial_code": "+49"},
    "DJ": {"name": "Djibouti", "dial_code": "+253"},
    "DK": {"name": "Denmark", "dial_code": "+45"},
    "DM": {"name": "Dominica", "dial_code": "+1-767"},
    "DO": {"name": "Dominican Republic", "dial_code": "+1-809"},
    "DZ": {"name": "Algeria", "dial_code": "+213"},
    "EC": {"name": "Ecuador", "dial_code": "+593"},
    "EE": {"name": "Estonia", "dial_code": "+372"},
    "EG": {"name": "Egypt", "dial_code": "+20"},
    "EH": {"name": "Western Sahara", "dial_code": "+212"},
    "ER": {"name": "Eritrea", "dial_code": "+291"},
    "ES": {"name": "Spain", "dial_code": "+34"},
    "ET": {"name": "Ethiopia", "dial_code": "+251"},
    "FI": {"name": "Finland", "dial_code": "+358"},
    "FJ": {"name": "Fiji", "dial_code": "+679"},
    "FK": {"name": "Falkland Islands", "dial_code": "+500"},
    "FM": {"name": "Micronesia", "dial_code": "+691"},
    "FO": {"name": "Faroe Islands", "dial_code": "+298"},
    "FR": {"name": "France", "dial_code": "+33"},
    "GA": {"name": "Gabon", "dial_code": "+241"},
    "GB": {"name": "United Kingdom", "dial_code": "+44"},
    "GD": {"name": "Grenada", "dial_code": "+1-473"},
    "GE": {"name": "Georgia", "dial_code": "+995"},
    "GF": {"name": "French Guiana", "dial_code": "+594"},
    "GG": {"name": "Guernsey", "dial_code": "+44"},
    "GH": {"name": "Ghana", "dial_code": "+233"},
    "GI": {"name": "Gibraltar", "dial_code": "+350"},
    "GL": {"name": "Greenland", "dial_code": "+299"},
    "GM": {"name": "Gambia", "dial_code": "+220"},
    "GN": {"name": "Guinea", "dial_code": "+224"},
    "GP": {"name": "Guadeloupe", "dial_code": "+590"},
    "GQ": {"name": "Equatorial Guinea", "dial_code": "+240"},
    "GR": {"name": "Greece", "dial_code": "+30"},
    "GS": {"name": "South Georgia and the South Sandwich Islands", "dial_code": "+500"},
    "GT": {"name": "Guatemala", "dial_code": "+502"},
    "GU": {"name": "Guam", "dial_code": "+1-671"},
    "GW": {"name": "Guinea-Bissau", "dial_code": "+245"},
    "GY": {"name": "Guyana", "dial_code": "+592"},
    "HK": {"name": "Hong Kong", "dial_code": "+852"},
    "HM": {"name": "Heard Island and McDonald Islands", "dial_code": "+672"},
    "HN": {"name": "Honduras", "dial_code": "+504"},
    "HR": {"name": "Croatia", "dial_code": "+385"},
    "HT": {"name": "Haiti", "dial_code": "+509"},
    "HU": {"name": "Hungary", "dial_code": "+36"},
    "ID": {"name": "Indonesia", "dial_code": "+62"},
    "IE": {"name": "Ireland", "dial_code": "+353"},
    "IL": {"name": "Israel", "dial_code": "+972"},
    "IM": {"name": "Isle of Man", "dial_code": "+44"},
    "IN": {"name": "India", "dial_code": "+91"},
    "IO": {"name": "British Indian Ocean Territory", "dial_code": "+246"},
    "IQ": {"name": "Iraq", "dial_code": "+964"},
    "IR": {"name": "Iran", "dial_code": "+98"},
    "IS": {"name": "Iceland", "dial_code": "+354"},
    "IT": {"name": "Italy", "dial_code": "+39"},
    "JE": {"name": "Jersey", "dial_code": "+44"},
    "JM": {"name": "Jamaica", "dial_code": "+1-876"},
    "JO": {"name": "Jordan", "dial_code": "+962"},
    "JP": {"name": "Japan", "dial_code": "+81"},
    "KE": {"name": "Kenya", "dial_code": "+254"},
    "KG": {"name": "Kyrgyzstan", "dial_code": "+996"},
    "KH": {"name": "Cambodia", "dial_code": "+855"},
    "KI": {"name": "Kiribati", "dial_code": "+686"},
    "KM": {"name": "Comoros", "dial_code": "+269"},
    "KN": {"name": "Saint Kitts and Nevis", "dial_code": "+1-869"},
    "KP": {"name": "North Korea", "dial_code": "+850"},
    "KR": {"name": "South Korea", "dial_code": "+82"},
    "KW": {"name": "Kuwait", "dial_code": "+965"},
    "KY": {"name": "Cayman Islands", "dial_code": "+1-345"},
    "KZ": {"name": "Kazakhstan", "dial_code": "+7"},
    "LA": {"name": "Laos", "dial_code": "+856"},
    "LB": {"name": "Lebanon", "dial_code": "+961"},
    "LC": {"name": "Saint Lucia", "dial_code": "+1-758"},
    "LI": {"name": "Liechtenstein", "dial_code": "+423"},
    "LK": {"name": "Sri Lanka", "dial_code": "+94"},
    "LR": {"name": "Liberia", "dial_code": "+231"},
    "LS": {"name": "Lesotho", "dial_code": "+266"},
    "LT": {"name": "Lithuania", "dial_code": "+370"},
    "LU": {"name": "Luxembourg", "dial_code": "+352"},
    "LV": {"name": "Latvia", "dial_code": "+371"},
    "LY": {"name": "Libya", "dial_code": "+218"},
    "MA": {"name": "Morocco", "dial_code": "+212"},
    "MC": {"name": "Monaco", "dial_code": "+377"},
    "MD": {"name": "Moldova", "dial_code": "+373"},
    "ME": {"name": "Montenegro", "dial_code": "+382"},
    "MF": {"name": "Saint Martin", "dial_code": "+590"},
    "MG": {"name": "Madagascar", "dial_code": "+261"},
    "MH": {"name": "Marshall Islands", "dial_code": "+692"},
    "MK": {"name": "North Macedonia", "dial_code": "+389"},
    "ML": {"name": "Mali", "dial_code": "+223"},
    "MM": {"name": "Myanmar", "dial_code": "+95"},
    "MN": {"name": "Mongolia", "dial_code": "+976"},
    "MO": {"name": "Macao", "dial_code": "+853"},
    "MP": {"name": "Northern Mariana Islands", "dial_code": "+1-670"},
    "MQ": {"name": "Martinique", "dial_code": "+596"},
    "MR": {"name": "Mauritania", "dial_code": "+222"},
    "MS": {"name": "Montserrat", "dial_code": "+1-664"},
    "MT": {"name": "Malta", "dial_code": "+356"},
    "MU": {"name": "Mauritius", "dial_code": "+230"},
    "MV": {"name": "Maldives", "dial_code": "+960"},
    "MW": {"name": "Malawi", "dial_code": "+265"},
    "MX": {"name": "Mexico", "dial_code": "+52"},
    "MY": {"name": "Malaysia", "dial_code": "+60"},
    "MZ": {"name": "Mozambique", "dial_code": "+258"},
    "NA": {"name": "Namibia", "dial_code": "+264"},
    "NC": {"name": "New Caledonia", "dial_code": "+687"},
    "NE": {"name": "Niger", "dial_code": "+227"},
    "NF": {"name": "Norfolk Island", "dial_code": "+672"},
    "NG": {"name": "Nigeria", "dial_code": "+234"},
    "NI": {"name": "Nicaragua", "dial_code": "+505"},
    "NL": {"name": "Netherlands", "dial_code": "+31"},
    "NO": {"name": "Norway", "dial_code": "+47"},
    "NP": {"name": "Nepal", "dial_code": "+977"},
    "NR": {"name": "Nauru", "dial_code": "+674"},
    "NU": {"name": "Niue", "dial_code": "+683"},
    "NZ": {"name": "New Zealand", "dial_code": "+64"},
    "OM": {"name": "Oman", "dial_code": "+968"},
    "PA": {"name": "Panama", "dial_code": "+507"},
    "PE": {"name": "Peru", "dial_code": "+51"},
    "PF": {"name": "French Polynesia", "dial_code": "+689"},
    "PG": {"name": "Papua New Guinea", "dial_code": "+675"},
    "PH": {"name": "Philippines", "dial_code": "+63"},
    "PK": {"name": "Pakistan", "dial_code": "+92"},
    "PL": {"name": "Poland", "dial_code": "+48"},
    "PM": {"name": "Saint Pierre and Miquelon", "dial_code": "+508"},
    "PN": {"name": "Pitcairn", "dial_code": "+64"},
    "PR": {"name": "Puerto Rico", "dial_code": "+1-787"},
    "PS": {"name": "Palestinian Territory", "dial_code": "+970"},
    "PT": {"name": "Portugal", "dial_code": "+351"},
    "PW": {"name": "Palau", "dial_code": "+680"},
    "PY": {"name": "Paraguay", "dial_code": "+595"},
    "QA": {"name": "Qatar", "dial_code": "+974"},
    "RE": {"name": "Reunion", "dial_code": "+262"},
    "RO": {"name": "Romania", "dial_code": "+40"},
    "RS": {"name": "Serbia", "dial_code": "+381"},
    "RU": {"name": "Russia", "dial_code": "+7"},
    "RW": {"name": "Rwanda", "dial_code": "+250"},
    "SA": {"name": "Saudi Arabia", "dial_code": "+966"},
    "SB": {"name": "Solomon Islands", "dial_code": "+677"},
    "SC": {"name": "Seychelles", "dial_code": "+248"},
    "SD": {"name": "Sudan", "dial_code": "+249"},
    "SE": {"name": "Sweden", "dial_code": "+46"},
    "SG": {"name": "Singapore", "dial_code": "+65"},
    "SH": {"name": "Saint Helena", "dial_code": "+290"},
    "SI": {"name": "Slovenia", "dial_code": "+386"},
    "SJ": {"name": "Svalbard and Jan Mayen", "dial_code": "+47"},
    "SK": {"name": "Slovakia", "dial_code": "+421"},
    "SL": {"name": "Sierra Leone", "dial_code": "+232"},
    "SM": {"name": "San Marino", "dial_code": "+378"},
    "SN": {"name": "Senegal", "dial_code": "+221"},
    "SO": {"name": "Somalia", "dial_code": "+252"},
    "SR": {"name": "Suriname", "dial_code": "+597"},
    "SS": {"name": "South Sudan", "dial_code": "+211"},
    "ST": {"name": "Sao Tome and Principe", "dial_code": "+239"},
    "SV": {"name": "El Salvador", "dial_code": "+503"},
    "SX": {"name": "Sint Maarten", "dial_code": "+1-721"},
    "SY": {"name": "Syria", "dial_code": "+963"},
    "SZ": {"name": "Swaziland", "dial_code": "+268"},
    "TC": {"name": "Turks and Caicos Islands", "dial_code": "+1-649"},
    "TD": {"name": "Chad", "dial_code": "+235"},
    "TF": {"name": "French Southern Territories", "dial_code": "+262"},
    "TG": {"name": "Togo", "dial_code": "+228"},
    "TH": {"name": "Thailand", "dial_code": "+66"},
    "TJ": {"name": "Tajikistan", "dial_code": "+992"},
    "TK": {"name": "Tokelau", "dial_code": "+690"},
    "TL": {"name": "East Timor", "dial_code": "+670"},
    "TM": {"name": "Turkmenistan", "dial_code": "+993"},
    "TN": {"name": "Tunisia", "dial_code": "+216"},
    "TO": {"name": "Tonga", "dial_code": "+676"},
    "TR": {"name": "Turkey", "dial_code": "+90"},
    "TT": {"name": "Trinidad and Tobago", "dial_code": "+1-868"},
    "TV": {"name": "Tuvalu", "dial_code": "+688"},
    "TW": {"name": "Taiwan", "dial_code": "+886"},
    "TZ": {"name": "Tanzania", "dial_code": "+255"},
    "UA": {"name": "Ukraine", "dial_code": "+380"},
    "UG": {"name": "Uganda", "dial_code": "+256"},
    "UM": {"name": "United States Minor Outlying Islands", "dial_code": "+1"},
    "US": {"name": "United States", "dial_code": "+1"},
    "UY": {"name": "Uruguay", "dial_code": "+598"},
    "UZ": {"name": "Uzbekistan", "dial_code": "+998"},
    "VA": {"name": "Vatican", "dial_code": "+379"},
    "VC": {"name": "Saint Vincent and the Grenadines", "dial_code": "+1-784"},
    "VE": {"name": "Venezuela", "dial_code": "+58"},
    "VG": {"name": "British Virgin Islands", "dial_code": "+1-284"},
    "VI": {"name": "US Virgin Islands", "dial_code": "+1-340"},
    "VN": {"name": "Vietnam", "dial_code": "+84"},
    "VU": {"name": "Vanuatu", "dial_code": "+678"},
    "WF": {"name": "Wallis and Futuna", "dial_code": "+681"},
    "WS": {"name": "Samoa", "dial_code": "+685"},
    "XK": {"name": "Kosovo", "dial_code": "+383"},
    "YE": {"name": "Yemen", "dial_code": "+967"},
    "YT": {"name": "Mayotte", "dial_code": "+262"},
    "ZA": {"name": "South Africa", "dial_code": "+27"},
    "ZM": {"name": "Zambia", "dial_code": "+260"},
    "ZW": {"name": "Zimbabwe", "dial_code": "+263"},
}

COUNTRY_CODES: Final[frozenset[str]] = frozenset(COUNTRIES.keys())

# fmt: off
# Extended metadata keyed by ISO alpha-2.  Fields:
#   alpha3, numeric, continent, region, capital,
#   currency_code, currency_name, languages, tld,
#   is_eu, is_eea, timezone
COUNTRY_META: Final[dict[str, CountryMeta]] = {
    "AD": {"alpha3": "AND", "numeric": "020", "continent": "Europe", "region": "Southern Europe", "capital": "Andorra la Vella", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["ca"], "tld": ".ad", "is_eu": False, "is_eea": False, "timezone": "Europe/Andorra"},
    "AE": {"alpha3": "ARE", "numeric": "784", "continent": "Asia", "region": "Western Asia", "capital": "Abu Dhabi", "currency_code": "AED", "currency_name": "UAE Dirham", "currency_symbol": "د.إ", "languages": ["ar"], "tld": ".ae", "is_eu": False, "is_eea": False, "timezone": "Asia/Dubai"},
    "AF": {"alpha3": "AFG", "numeric": "004", "continent": "Asia", "region": "Southern Asia", "capital": "Kabul", "currency_code": "AFN", "currency_name": "Afghan Afghani", "currency_symbol": "؋", "languages": ["ps", "uz", "tk"], "tld": ".af", "is_eu": False, "is_eea": False, "timezone": "Asia/Kabul"},
    "AG": {"alpha3": "ATG", "numeric": "028", "continent": "North America", "region": "Caribbean", "capital": "Saint John's", "currency_code": "XCD", "currency_name": "East Caribbean Dollar", "currency_symbol": "EC$", "languages": ["en"], "tld": ".ag", "is_eu": False, "is_eea": False, "timezone": "America/Antigua"},
    "AI": {"alpha3": "AIA", "numeric": "660", "continent": "North America", "region": "Caribbean", "capital": "The Valley", "currency_code": "XCD", "currency_name": "East Caribbean Dollar", "currency_symbol": "EC$", "languages": ["en"], "tld": ".ai", "is_eu": False, "is_eea": False, "timezone": "America/Anguilla"},
    "AL": {"alpha3": "ALB", "numeric": "008", "continent": "Europe", "region": "Southern Europe", "capital": "Tirana", "currency_code": "ALL", "currency_name": "Albanian Lek", "currency_symbol": "L", "languages": ["sq"], "tld": ".al", "is_eu": False, "is_eea": False, "timezone": "Europe/Tirane"},
    "AM": {"alpha3": "ARM", "numeric": "051", "continent": "Asia", "region": "Western Asia", "capital": "Yerevan", "currency_code": "AMD", "currency_name": "Armenian Dram", "currency_symbol": "֏", "languages": ["hy", "ru"], "tld": ".am", "is_eu": False, "is_eea": False, "timezone": "Asia/Yerevan"},
    "AO": {"alpha3": "AGO", "numeric": "024", "continent": "Africa", "region": "Middle Africa", "capital": "Luanda", "currency_code": "AOA", "currency_name": "Angolan Kwanza", "currency_symbol": "Kz", "languages": ["pt"], "tld": ".ao", "is_eu": False, "is_eea": False, "timezone": "Africa/Luanda"},
    "AQ": {"alpha3": "ATA", "numeric": "010", "continent": "Antarctica", "region": "Antarctica", "capital": "", "currency_code": "", "currency_name": "", "currency_symbol": "", "languages": [], "tld": ".aq", "is_eu": False, "is_eea": False, "timezone": "Antarctica/McMurdo"},
    "AR": {"alpha3": "ARG", "numeric": "032", "continent": "South America", "region": "South America", "capital": "Buenos Aires", "currency_code": "ARS", "currency_name": "Argentine Peso", "currency_symbol": "$", "languages": ["es"], "tld": ".ar", "is_eu": False, "is_eea": False, "timezone": "America/Argentina/Buenos_Aires"},
    "AS": {"alpha3": "ASM", "numeric": "016", "continent": "Oceania", "region": "Polynesia", "capital": "Pago Pago", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en", "sm"], "tld": ".as", "is_eu": False, "is_eea": False, "timezone": "Pacific/Pago_Pago"},
    "AT": {"alpha3": "AUT", "numeric": "040", "continent": "Europe", "region": "Western Europe", "capital": "Vienna", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["de"], "tld": ".at", "is_eu": True, "is_eea": True, "timezone": "Europe/Vienna"},
    "AU": {"alpha3": "AUS", "numeric": "036", "continent": "Oceania", "region": "Australia and New Zealand", "capital": "Canberra", "currency_code": "AUD", "currency_name": "Australian Dollar", "currency_symbol": "A$", "languages": ["en"], "tld": ".au", "is_eu": False, "is_eea": False, "timezone": "Australia/Sydney"},
    "AW": {"alpha3": "ABW", "numeric": "533", "continent": "North America", "region": "Caribbean", "capital": "Oranjestad", "currency_code": "AWG", "currency_name": "Aruban Florin", "currency_symbol": "ƒ", "languages": ["nl", "pap"], "tld": ".aw", "is_eu": False, "is_eea": False, "timezone": "America/Aruba"},
    "AX": {"alpha3": "ALA", "numeric": "248", "continent": "Europe", "region": "Northern Europe", "capital": "Mariehamn", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["sv"], "tld": ".ax", "is_eu": True, "is_eea": True, "timezone": "Europe/Mariehamn"},
    "AZ": {"alpha3": "AZE", "numeric": "031", "continent": "Asia", "region": "Western Asia", "capital": "Baku", "currency_code": "AZN", "currency_name": "Azerbaijani Manat", "currency_symbol": "₼", "languages": ["az"], "tld": ".az", "is_eu": False, "is_eea": False, "timezone": "Asia/Baku"},
    "BA": {"alpha3": "BIH", "numeric": "070", "continent": "Europe", "region": "Southern Europe", "capital": "Sarajevo", "currency_code": "BAM", "currency_name": "Bosnia-Herzegovina Convertible Mark", "currency_symbol": "KM", "languages": ["bs", "hr", "sr"], "tld": ".ba", "is_eu": False, "is_eea": False, "timezone": "Europe/Sarajevo"},
    "BB": {"alpha3": "BRB", "numeric": "052", "continent": "North America", "region": "Caribbean", "capital": "Bridgetown", "currency_code": "BBD", "currency_name": "Barbadian Dollar", "currency_symbol": "Bds$", "languages": ["en"], "tld": ".bb", "is_eu": False, "is_eea": False, "timezone": "America/Barbados"},
    "BD": {"alpha3": "BGD", "numeric": "050", "continent": "Asia", "region": "Southern Asia", "capital": "Dhaka", "currency_code": "BDT", "currency_name": "Bangladeshi Taka", "currency_symbol": "৳", "languages": ["bn"], "tld": ".bd", "is_eu": False, "is_eea": False, "timezone": "Asia/Dhaka"},
    "BE": {"alpha3": "BEL", "numeric": "056", "continent": "Europe", "region": "Western Europe", "capital": "Brussels", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["nl", "fr", "de"], "tld": ".be", "is_eu": True, "is_eea": True, "timezone": "Europe/Brussels"},
    "BF": {"alpha3": "BFA", "numeric": "854", "continent": "Africa", "region": "Western Africa", "capital": "Ouagadougou", "currency_code": "XOF", "currency_name": "West African CFA Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".bf", "is_eu": False, "is_eea": False, "timezone": "Africa/Ouagadougou"},
    "BG": {"alpha3": "BGR", "numeric": "100", "continent": "Europe", "region": "Eastern Europe", "capital": "Sofia", "currency_code": "BGN", "currency_name": "Bulgarian Lev", "currency_symbol": "лв", "languages": ["bg"], "tld": ".bg", "is_eu": True, "is_eea": True, "timezone": "Europe/Sofia"},
    "BH": {"alpha3": "BHR", "numeric": "048", "continent": "Asia", "region": "Western Asia", "capital": "Manama", "currency_code": "BHD", "currency_name": "Bahraini Dinar", "currency_symbol": ".د.ب", "languages": ["ar"], "tld": ".bh", "is_eu": False, "is_eea": False, "timezone": "Asia/Bahrain"},
    "BI": {"alpha3": "BDI", "numeric": "108", "continent": "Africa", "region": "Eastern Africa", "capital": "Gitega", "currency_code": "BIF", "currency_name": "Burundian Franc", "currency_symbol": "Fr", "languages": ["fr", "rn"], "tld": ".bi", "is_eu": False, "is_eea": False, "timezone": "Africa/Bujumbura"},
    "BJ": {"alpha3": "BEN", "numeric": "204", "continent": "Africa", "region": "Western Africa", "capital": "Porto-Novo", "currency_code": "XOF", "currency_name": "West African CFA Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".bj", "is_eu": False, "is_eea": False, "timezone": "Africa/Porto-Novo"},
    "BL": {"alpha3": "BLM", "numeric": "652", "continent": "North America", "region": "Caribbean", "capital": "Gustavia", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".bl", "is_eu": False, "is_eea": False, "timezone": "America/St_Barthelemy"},
    "BM": {"alpha3": "BMU", "numeric": "060", "continent": "North America", "region": "Northern America", "capital": "Hamilton", "currency_code": "BMD", "currency_name": "Bermudian Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".bm", "is_eu": False, "is_eea": False, "timezone": "Atlantic/Bermuda"},
    "BN": {"alpha3": "BRN", "numeric": "096", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Bandar Seri Begawan", "currency_code": "BND", "currency_name": "Brunei Dollar", "currency_symbol": "B$", "languages": ["ms"], "tld": ".bn", "is_eu": False, "is_eea": False, "timezone": "Asia/Brunei"},
    "BO": {"alpha3": "BOL", "numeric": "068", "continent": "South America", "region": "South America", "capital": "Sucre", "currency_code": "BOB", "currency_name": "Bolivian Boliviano", "currency_symbol": "Bs.", "languages": ["es", "ay", "qu"], "tld": ".bo", "is_eu": False, "is_eea": False, "timezone": "America/La_Paz"},
    "BQ": {"alpha3": "BES", "numeric": "535", "continent": "North America", "region": "Caribbean", "capital": "Kralendijk", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["nl"], "tld": ".bq", "is_eu": False, "is_eea": False, "timezone": "America/Kralendijk"},
    "BR": {"alpha3": "BRA", "numeric": "076", "continent": "South America", "region": "South America", "capital": "Brasilia", "currency_code": "BRL", "currency_name": "Brazilian Real", "currency_symbol": "R$", "languages": ["pt"], "tld": ".br", "is_eu": False, "is_eea": False, "timezone": "America/Sao_Paulo"},
    "BS": {"alpha3": "BHS", "numeric": "044", "continent": "North America", "region": "Caribbean", "capital": "Nassau", "currency_code": "BSD", "currency_name": "Bahamian Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".bs", "is_eu": False, "is_eea": False, "timezone": "America/Nassau"},
    "BT": {"alpha3": "BTN", "numeric": "064", "continent": "Asia", "region": "Southern Asia", "capital": "Thimphu", "currency_code": "BTN", "currency_name": "Bhutanese Ngultrum", "currency_symbol": "Nu", "languages": ["dz"], "tld": ".bt", "is_eu": False, "is_eea": False, "timezone": "Asia/Thimphu"},
    "BV": {"alpha3": "BVT", "numeric": "074", "continent": "Antarctica", "region": "Antarctica", "capital": "", "currency_code": "NOK", "currency_name": "Norwegian Krone", "currency_symbol": "kr", "languages": [], "tld": ".bv", "is_eu": False, "is_eea": False, "timezone": "Europe/Oslo"},
    "BW": {"alpha3": "BWA", "numeric": "072", "continent": "Africa", "region": "Southern Africa", "capital": "Gaborone", "currency_code": "BWP", "currency_name": "Botswanan Pula", "currency_symbol": "P", "languages": ["en", "tn"], "tld": ".bw", "is_eu": False, "is_eea": False, "timezone": "Africa/Gaborone"},
    "BY": {"alpha3": "BLR", "numeric": "112", "continent": "Europe", "region": "Eastern Europe", "capital": "Minsk", "currency_code": "BYR", "currency_name": "Belarusian Ruble", "currency_symbol": "Br", "languages": ["be", "ru"], "tld": ".by", "is_eu": False, "is_eea": False, "timezone": "Europe/Minsk"},
    "BZ": {"alpha3": "BLZ", "numeric": "084", "continent": "North America", "region": "Central America", "capital": "Belmopan", "currency_code": "BZD", "currency_name": "Belize Dollar", "currency_symbol": "BZ$", "languages": ["en"], "tld": ".bz", "is_eu": False, "is_eea": False, "timezone": "America/Belize"},
    "CA": {"alpha3": "CAN", "numeric": "124", "continent": "North America", "region": "Northern America", "capital": "Ottawa", "currency_code": "CAD", "currency_name": "Canadian Dollar", "currency_symbol": "CA$", "languages": ["en", "fr"], "tld": ".ca", "is_eu": False, "is_eea": False, "timezone": "America/Toronto"},
    "CC": {"alpha3": "CCK", "numeric": "166", "continent": "Asia", "region": "Australian Territories", "capital": "West Island", "currency_code": "AUD", "currency_name": "Australian Dollar", "currency_symbol": "A$", "languages": ["ms"], "tld": ".cc", "is_eu": False, "is_eea": False, "timezone": "Indian/Cocos"},
    "CD": {"alpha3": "COD", "numeric": "180", "continent": "Africa", "region": "Middle Africa", "capital": "Kinshasa", "currency_code": "CDF", "currency_name": "Congolese Franc", "currency_symbol": "Fr", "languages": ["fr", "ln", "kg", "sw", "lu"], "tld": ".cd", "is_eu": False, "is_eea": False, "timezone": "Africa/Kinshasa"},
    "CF": {"alpha3": "CAF", "numeric": "140", "continent": "Africa", "region": "Middle Africa", "capital": "Bangui", "currency_code": "XAF", "currency_name": "Central African CFA Franc", "currency_symbol": "Fr", "languages": ["fr", "sg"], "tld": ".cf", "is_eu": False, "is_eea": False, "timezone": "Africa/Bangui"},
    "CG": {"alpha3": "COG", "numeric": "178", "continent": "Africa", "region": "Middle Africa", "capital": "Brazzaville", "currency_code": "XAF", "currency_name": "Central African CFA Franc", "currency_symbol": "Fr", "languages": ["fr", "ln"], "tld": ".cg", "is_eu": False, "is_eea": False, "timezone": "Africa/Brazzaville"},
    "CH": {"alpha3": "CHE", "numeric": "756", "continent": "Europe", "region": "Western Europe", "capital": "Bern", "currency_code": "CHF", "currency_name": "Swiss Franc", "currency_symbol": "CHF", "languages": ["de", "fr", "it"], "tld": ".ch", "is_eu": False, "is_eea": False, "timezone": "Europe/Zurich"},
    "CI": {"alpha3": "CIV", "numeric": "384", "continent": "Africa", "region": "Western Africa", "capital": "Yamoussoukro", "currency_code": "XOF", "currency_name": "West African CFA Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".ci", "is_eu": False, "is_eea": False, "timezone": "Africa/Abidjan"},
    "CK": {"alpha3": "COK", "numeric": "184", "continent": "Oceania", "region": "Polynesia", "capital": "Avarua", "currency_code": "NZD", "currency_name": "New Zealand Dollar", "currency_symbol": "NZ$", "languages": ["en"], "tld": ".ck", "is_eu": False, "is_eea": False, "timezone": "Pacific/Rarotonga"},
    "CL": {"alpha3": "CHL", "numeric": "152", "continent": "South America", "region": "South America", "capital": "Santiago", "currency_code": "CLP", "currency_name": "Chilean Peso", "currency_symbol": "$", "languages": ["es"], "tld": ".cl", "is_eu": False, "is_eea": False, "timezone": "America/Santiago"},
    "CM": {"alpha3": "CMR", "numeric": "120", "continent": "Africa", "region": "Middle Africa", "capital": "Yaounde", "currency_code": "XAF", "currency_name": "Central African CFA Franc", "currency_symbol": "Fr", "languages": ["en", "fr"], "tld": ".cm", "is_eu": False, "is_eea": False, "timezone": "Africa/Douala"},
    "CN": {"alpha3": "CHN", "numeric": "156", "continent": "Asia", "region": "Eastern Asia", "capital": "Beijing", "currency_code": "CNY", "currency_name": "Chinese Yuan", "currency_symbol": "¥", "languages": ["zh"], "tld": ".cn", "is_eu": False, "is_eea": False, "timezone": "Asia/Shanghai"},
    "CO": {"alpha3": "COL", "numeric": "170", "continent": "South America", "region": "South America", "capital": "Bogota", "currency_code": "COP", "currency_name": "Colombian Peso", "currency_symbol": "$", "languages": ["es"], "tld": ".co", "is_eu": False, "is_eea": False, "timezone": "America/Bogota"},
    "CR": {"alpha3": "CRI", "numeric": "188", "continent": "North America", "region": "Central America", "capital": "San Jose", "currency_code": "CRC", "currency_name": "Costa Rican Colon", "currency_symbol": "₡", "languages": ["es"], "tld": ".cr", "is_eu": False, "is_eea": False, "timezone": "America/Costa_Rica"},
    "CU": {"alpha3": "CUB", "numeric": "192", "continent": "North America", "region": "Caribbean", "capital": "Havana", "currency_code": "CUP", "currency_name": "Cuban Peso", "currency_symbol": "$", "languages": ["es"], "tld": ".cu", "is_eu": False, "is_eea": False, "timezone": "America/Havana"},
    "CV": {"alpha3": "CPV", "numeric": "132", "continent": "Africa", "region": "Western Africa", "capital": "Praia", "currency_code": "CVE", "currency_name": "Cape Verdean Escudo", "currency_symbol": "$", "languages": ["pt"], "tld": ".cv", "is_eu": False, "is_eea": False, "timezone": "Atlantic/Cape_Verde"},
    "CW": {"alpha3": "CUW", "numeric": "531", "continent": "North America", "region": "Caribbean", "capital": "Willemstad", "currency_code": "ANG", "currency_name": "Netherlands Antillean Guilder", "currency_symbol": "ƒ", "languages": ["nl", "pap"], "tld": ".cw", "is_eu": False, "is_eea": False, "timezone": "America/Curacao"},
    "CX": {"alpha3": "CXR", "numeric": "162", "continent": "Asia", "region": "Australian Territories", "capital": "Flying Fish Cove", "currency_code": "AUD", "currency_name": "Australian Dollar", "currency_symbol": "A$", "languages": ["en"], "tld": ".cx", "is_eu": False, "is_eea": False, "timezone": "Indian/Christmas"},
    "CY": {"alpha3": "CYP", "numeric": "196", "continent": "Asia", "region": "Western Asia", "capital": "Nicosia", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["el", "tr"], "tld": ".cy", "is_eu": True, "is_eea": True, "timezone": "Asia/Nicosia"},
    "CZ": {"alpha3": "CZE", "numeric": "203", "continent": "Europe", "region": "Eastern Europe", "capital": "Prague", "currency_code": "CZK", "currency_name": "Czech Koruna", "currency_symbol": "Kč", "languages": ["cs"], "tld": ".cz", "is_eu": True, "is_eea": True, "timezone": "Europe/Prague"},
    "DE": {"alpha3": "DEU", "numeric": "276", "continent": "Europe", "region": "Western Europe", "capital": "Berlin", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["de"], "tld": ".de", "is_eu": True, "is_eea": True, "timezone": "Europe/Berlin"},
    "DJ": {"alpha3": "DJI", "numeric": "262", "continent": "Africa", "region": "Eastern Africa", "capital": "Djibouti", "currency_code": "DJF", "currency_name": "Djiboutian Franc", "currency_symbol": "Fr", "languages": ["fr", "ar"], "tld": ".dj", "is_eu": False, "is_eea": False, "timezone": "Africa/Djibouti"},
    "DK": {"alpha3": "DNK", "numeric": "208", "continent": "Europe", "region": "Northern Europe", "capital": "Copenhagen", "currency_code": "DKK", "currency_name": "Danish Krone", "currency_symbol": "kr", "languages": ["da"], "tld": ".dk", "is_eu": True, "is_eea": True, "timezone": "Europe/Copenhagen"},
    "DM": {"alpha3": "DMA", "numeric": "212", "continent": "North America", "region": "Caribbean", "capital": "Roseau", "currency_code": "XCD", "currency_name": "East Caribbean Dollar", "currency_symbol": "EC$", "languages": ["en"], "tld": ".dm", "is_eu": False, "is_eea": False, "timezone": "America/Dominica"},
    "DO": {"alpha3": "DOM", "numeric": "214", "continent": "North America", "region": "Caribbean", "capital": "Santo Domingo", "currency_code": "DOP", "currency_name": "Dominican Peso", "currency_symbol": "RD$", "languages": ["es"], "tld": ".do", "is_eu": False, "is_eea": False, "timezone": "America/Santo_Domingo"},
    "DZ": {"alpha3": "DZA", "numeric": "012", "continent": "Africa", "region": "Northern Africa", "capital": "Algiers", "currency_code": "DZD", "currency_name": "Algerian Dinar", "currency_symbol": "دج", "languages": ["ar"], "tld": ".dz", "is_eu": False, "is_eea": False, "timezone": "Africa/Algiers"},
    "EC": {"alpha3": "ECU", "numeric": "218", "continent": "South America", "region": "South America", "capital": "Quito", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["es"], "tld": ".ec", "is_eu": False, "is_eea": False, "timezone": "America/Guayaquil"},
    "EE": {"alpha3": "EST", "numeric": "233", "continent": "Europe", "region": "Northern Europe", "capital": "Tallinn", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["et"], "tld": ".ee", "is_eu": True, "is_eea": True, "timezone": "Europe/Tallinn"},
    "EG": {"alpha3": "EGY", "numeric": "818", "continent": "Africa", "region": "Northern Africa", "capital": "Cairo", "currency_code": "EGP", "currency_name": "Egyptian Pound", "currency_symbol": "£", "languages": ["ar"], "tld": ".eg", "is_eu": False, "is_eea": False, "timezone": "Africa/Cairo"},
    "EH": {"alpha3": "ESH", "numeric": "732", "continent": "Africa", "region": "Northern Africa", "capital": "El Aaiun", "currency_code": "MAD", "currency_name": "Moroccan Dirham", "currency_symbol": "MAD", "languages": ["ar"], "tld": ".eh", "is_eu": False, "is_eea": False, "timezone": "Africa/El_Aaiun"},
    "ER": {"alpha3": "ERI", "numeric": "232", "continent": "Africa", "region": "Eastern Africa", "capital": "Asmara", "currency_code": "ERN", "currency_name": "Eritrean Nakfa", "currency_symbol": "Nfk", "languages": ["ti", "ar", "en"], "tld": ".er", "is_eu": False, "is_eea": False, "timezone": "Africa/Asmara"},
    "ES": {"alpha3": "ESP", "numeric": "724", "continent": "Europe", "region": "Southern Europe", "capital": "Madrid", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["es"], "tld": ".es", "is_eu": True, "is_eea": True, "timezone": "Europe/Madrid"},
    "ET": {"alpha3": "ETH", "numeric": "231", "continent": "Africa", "region": "Eastern Africa", "capital": "Addis Ababa", "currency_code": "ETB", "currency_name": "Ethiopian Birr", "currency_symbol": "Br", "languages": ["am"], "tld": ".et", "is_eu": False, "is_eea": False, "timezone": "Africa/Addis_Ababa"},
    "FI": {"alpha3": "FIN", "numeric": "246", "continent": "Europe", "region": "Northern Europe", "capital": "Helsinki", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fi", "sv"], "tld": ".fi", "is_eu": True, "is_eea": True, "timezone": "Europe/Helsinki"},
    "FJ": {"alpha3": "FJI", "numeric": "242", "continent": "Oceania", "region": "Melanesia", "capital": "Suva", "currency_code": "FJD", "currency_name": "Fijian Dollar", "currency_symbol": "FJ$", "languages": ["en", "fj", "hi", "ur"], "tld": ".fj", "is_eu": False, "is_eea": False, "timezone": "Pacific/Fiji"},
    "FK": {"alpha3": "FLK", "numeric": "238", "continent": "South America", "region": "South America", "capital": "Stanley", "currency_code": "FKP", "currency_name": "Falkland Islands Pound", "currency_symbol": "£", "languages": ["en"], "tld": ".fk", "is_eu": False, "is_eea": False, "timezone": "Atlantic/Stanley"},
    "FM": {"alpha3": "FSM", "numeric": "583", "continent": "Oceania", "region": "Micronesia", "capital": "Palikir", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".fm", "is_eu": False, "is_eea": False, "timezone": "Pacific/Pohnpei"},
    "FO": {"alpha3": "FRO", "numeric": "234", "continent": "Europe", "region": "Northern Europe", "capital": "Torshavn", "currency_code": "DKK", "currency_name": "Danish Krone", "currency_symbol": "kr", "languages": ["fo"], "tld": ".fo", "is_eu": False, "is_eea": False, "timezone": "Atlantic/Faroe"},
    "FR": {"alpha3": "FRA", "numeric": "250", "continent": "Europe", "region": "Western Europe", "capital": "Paris", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".fr", "is_eu": True, "is_eea": True, "timezone": "Europe/Paris"},
    "GA": {"alpha3": "GAB", "numeric": "266", "continent": "Africa", "region": "Middle Africa", "capital": "Libreville", "currency_code": "XAF", "currency_name": "Central African CFA Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".ga", "is_eu": False, "is_eea": False, "timezone": "Africa/Libreville"},
    "GB": {"alpha3": "GBR", "numeric": "826", "continent": "Europe", "region": "Northern Europe", "capital": "London", "currency_code": "GBP", "currency_name": "British Pound", "currency_symbol": "£", "languages": ["en"], "tld": ".gb", "is_eu": False, "is_eea": False, "timezone": "Europe/London"},
    "GD": {"alpha3": "GRD", "numeric": "308", "continent": "North America", "region": "Caribbean", "capital": "Saint George's", "currency_code": "XCD", "currency_name": "East Caribbean Dollar", "currency_symbol": "EC$", "languages": ["en"], "tld": ".gd", "is_eu": False, "is_eea": False, "timezone": "America/Grenada"},
    "GE": {"alpha3": "GEO", "numeric": "268", "continent": "Asia", "region": "Western Asia", "capital": "Tbilisi", "currency_code": "GEL", "currency_name": "Georgian Lari", "currency_symbol": "₾", "languages": ["ka"], "tld": ".ge", "is_eu": False, "is_eea": False, "timezone": "Asia/Tbilisi"},
    "GF": {"alpha3": "GUF", "numeric": "254", "continent": "South America", "region": "South America", "capital": "Cayenne", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".gf", "is_eu": False, "is_eea": False, "timezone": "America/Cayenne"},
    "GG": {"alpha3": "GGY", "numeric": "831", "continent": "Europe", "region": "Northern Europe", "capital": "Saint Peter Port", "currency_code": "GBP", "currency_name": "British Pound", "currency_symbol": "£", "languages": ["en", "fr"], "tld": ".gg", "is_eu": False, "is_eea": False, "timezone": "Europe/Guernsey"},
    "GH": {"alpha3": "GHA", "numeric": "288", "continent": "Africa", "region": "Western Africa", "capital": "Accra", "currency_code": "GHS", "currency_name": "Ghanaian Cedi", "currency_symbol": "₵", "languages": ["en"], "tld": ".gh", "is_eu": False, "is_eea": False, "timezone": "Africa/Accra"},
    "GI": {"alpha3": "GIB", "numeric": "292", "continent": "Europe", "region": "Southern Europe", "capital": "Gibraltar", "currency_code": "GIP", "currency_name": "Gibraltar Pound", "currency_symbol": "£", "languages": ["en"], "tld": ".gi", "is_eu": False, "is_eea": False, "timezone": "Europe/Gibraltar"},
    "GL": {"alpha3": "GRL", "numeric": "304", "continent": "North America", "region": "Northern America", "capital": "Nuuk", "currency_code": "DKK", "currency_name": "Danish Krone", "currency_symbol": "kr", "languages": ["kl"], "tld": ".gl", "is_eu": False, "is_eea": False, "timezone": "America/Godthab"},
    "GM": {"alpha3": "GMB", "numeric": "270", "continent": "Africa", "region": "Western Africa", "capital": "Banjul", "currency_code": "GMD", "currency_name": "Gambian Dalasi", "currency_symbol": "D", "languages": ["en"], "tld": ".gm", "is_eu": False, "is_eea": False, "timezone": "Africa/Banjul"},
    "GN": {"alpha3": "GIN", "numeric": "324", "continent": "Africa", "region": "Western Africa", "capital": "Conakry", "currency_code": "GNF", "currency_name": "Guinean Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".gn", "is_eu": False, "is_eea": False, "timezone": "Africa/Conakry"},
    "GP": {"alpha3": "GLP", "numeric": "312", "continent": "North America", "region": "Caribbean", "capital": "Basse-Terre", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".gp", "is_eu": False, "is_eea": False, "timezone": "America/Guadeloupe"},
    "GQ": {"alpha3": "GNQ", "numeric": "226", "continent": "Africa", "region": "Middle Africa", "capital": "Malabo", "currency_code": "XAF", "currency_name": "Central African CFA Franc", "currency_symbol": "Fr", "languages": ["es", "fr"], "tld": ".gq", "is_eu": False, "is_eea": False, "timezone": "Africa/Malabo"},
    "GR": {"alpha3": "GRC", "numeric": "300", "continent": "Europe", "region": "Southern Europe", "capital": "Athens", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["el"], "tld": ".gr", "is_eu": True, "is_eea": True, "timezone": "Europe/Athens"},
    "GS": {"alpha3": "SGS", "numeric": "239", "continent": "Antarctica", "region": "Antarctica", "capital": "King Edward Point", "currency_code": "GBP", "currency_name": "British Pound", "currency_symbol": "£", "languages": ["en"], "tld": ".gs", "is_eu": False, "is_eea": False, "timezone": "Atlantic/South_Georgia"},
    "GT": {"alpha3": "GTM", "numeric": "320", "continent": "North America", "region": "Central America", "capital": "Guatemala City", "currency_code": "GTQ", "currency_name": "Guatemalan Quetzal", "currency_symbol": "Q", "languages": ["es"], "tld": ".gt", "is_eu": False, "is_eea": False, "timezone": "America/Guatemala"},
    "GU": {"alpha3": "GUM", "numeric": "316", "continent": "Oceania", "region": "Micronesia", "capital": "Hagatna", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en", "ch"], "tld": ".gu", "is_eu": False, "is_eea": False, "timezone": "Pacific/Guam"},
    "GW": {"alpha3": "GNB", "numeric": "624", "continent": "Africa", "region": "Western Africa", "capital": "Bissau", "currency_code": "XOF", "currency_name": "West African CFA Franc", "currency_symbol": "Fr", "languages": ["pt"], "tld": ".gw", "is_eu": False, "is_eea": False, "timezone": "Africa/Bissau"},
    "GY": {"alpha3": "GUY", "numeric": "328", "continent": "South America", "region": "South America", "capital": "Georgetown", "currency_code": "GYD", "currency_name": "Guyanaese Dollar", "currency_symbol": "G$", "languages": ["en"], "tld": ".gy", "is_eu": False, "is_eea": False, "timezone": "America/Guyana"},
    "HK": {"alpha3": "HKG", "numeric": "344", "continent": "Asia", "region": "Eastern Asia", "capital": "Hong Kong", "currency_code": "HKD", "currency_name": "Hong Kong Dollar", "currency_symbol": "HK$", "languages": ["zh", "en"], "tld": ".hk", "is_eu": False, "is_eea": False, "timezone": "Asia/Hong_Kong"},
    "HM": {"alpha3": "HMD", "numeric": "334", "continent": "Antarctica", "region": "Antarctica", "capital": "", "currency_code": "AUD", "currency_name": "Australian Dollar", "currency_symbol": "A$", "languages": [], "tld": ".hm", "is_eu": False, "is_eea": False, "timezone": "Indian/Kerguelen"},
    "HN": {"alpha3": "HND", "numeric": "340", "continent": "North America", "region": "Central America", "capital": "Tegucigalpa", "currency_code": "HNL", "currency_name": "Honduran Lempira", "currency_symbol": "L", "languages": ["es"], "tld": ".hn", "is_eu": False, "is_eea": False, "timezone": "America/Tegucigalpa"},
    "HR": {"alpha3": "HRV", "numeric": "191", "continent": "Europe", "region": "Southern Europe", "capital": "Zagreb", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["hr"], "tld": ".hr", "is_eu": True, "is_eea": True, "timezone": "Europe/Zagreb"},
    "HT": {"alpha3": "HTI", "numeric": "332", "continent": "North America", "region": "Caribbean", "capital": "Port-au-Prince", "currency_code": "HTG", "currency_name": "Haitian Gourde", "currency_symbol": "G", "languages": ["fr", "ht"], "tld": ".ht", "is_eu": False, "is_eea": False, "timezone": "America/Port-au-Prince"},
    "HU": {"alpha3": "HUN", "numeric": "348", "continent": "Europe", "region": "Eastern Europe", "capital": "Budapest", "currency_code": "HUF", "currency_name": "Hungarian Forint", "currency_symbol": "Ft", "languages": ["hu"], "tld": ".hu", "is_eu": True, "is_eea": True, "timezone": "Europe/Budapest"},
    "ID": {"alpha3": "IDN", "numeric": "360", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Jakarta", "currency_code": "IDR", "currency_name": "Indonesian Rupiah", "currency_symbol": "Rp", "languages": ["id"], "tld": ".id", "is_eu": False, "is_eea": False, "timezone": "Asia/Jakarta"},
    "IE": {"alpha3": "IRL", "numeric": "372", "continent": "Europe", "region": "Northern Europe", "capital": "Dublin", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["en", "ga"], "tld": ".ie", "is_eu": True, "is_eea": True, "timezone": "Europe/Dublin"},
    "IL": {"alpha3": "ISR", "numeric": "376", "continent": "Asia", "region": "Western Asia", "capital": "Jerusalem", "currency_code": "ILS", "currency_name": "Israeli New Shekel", "currency_symbol": "₪", "languages": ["he", "ar"], "tld": ".il", "is_eu": False, "is_eea": False, "timezone": "Asia/Jerusalem"},
    "IM": {"alpha3": "IMN", "numeric": "833", "continent": "Europe", "region": "Northern Europe", "capital": "Douglas", "currency_code": "GBP", "currency_name": "British Pound", "currency_symbol": "£", "languages": ["en", "gv"], "tld": ".im", "is_eu": False, "is_eea": False, "timezone": "Europe/Isle_of_Man"},
    "IN": {"alpha3": "IND", "numeric": "356", "continent": "Asia", "region": "Southern Asia", "capital": "New Delhi", "currency_code": "INR", "currency_name": "Indian Rupee", "currency_symbol": "₹", "languages": ["en", "hi"], "tld": ".in", "is_eu": False, "is_eea": False, "timezone": "Asia/Kolkata"},
    "IO": {"alpha3": "IOT", "numeric": "086", "continent": "Asia", "region": "Southern Asia", "capital": "Diego Garcia", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".io", "is_eu": False, "is_eea": False, "timezone": "Indian/Chagos"},
    "IQ": {"alpha3": "IRQ", "numeric": "368", "continent": "Asia", "region": "Western Asia", "capital": "Baghdad", "currency_code": "IQD", "currency_name": "Iraqi Dinar", "currency_symbol": "ع.د", "languages": ["ar", "ku"], "tld": ".iq", "is_eu": False, "is_eea": False, "timezone": "Asia/Baghdad"},
    "IR": {"alpha3": "IRN", "numeric": "364", "continent": "Asia", "region": "Southern Asia", "capital": "Tehran", "currency_code": "IRR", "currency_name": "Iranian Rial", "currency_symbol": "﷼", "languages": ["fa"], "tld": ".ir", "is_eu": False, "is_eea": False, "timezone": "Asia/Tehran"},
    "IS": {"alpha3": "ISL", "numeric": "352", "continent": "Europe", "region": "Northern Europe", "capital": "Reykjavik", "currency_code": "ISK", "currency_name": "Icelandic Krona", "currency_symbol": "kr", "languages": ["is"], "tld": ".is", "is_eu": False, "is_eea": True, "timezone": "Atlantic/Reykjavik"},
    "IT": {"alpha3": "ITA", "numeric": "380", "continent": "Europe", "region": "Southern Europe", "capital": "Rome", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["it"], "tld": ".it", "is_eu": True, "is_eea": True, "timezone": "Europe/Rome"},
    "JE": {"alpha3": "JEY", "numeric": "832", "continent": "Europe", "region": "Northern Europe", "capital": "Saint Helier", "currency_code": "GBP", "currency_name": "British Pound", "currency_symbol": "£", "languages": ["en", "fr"], "tld": ".je", "is_eu": False, "is_eea": False, "timezone": "Europe/Jersey"},
    "JM": {"alpha3": "JAM", "numeric": "388", "continent": "North America", "region": "Caribbean", "capital": "Kingston", "currency_code": "JMD", "currency_name": "Jamaican Dollar", "currency_symbol": "J$", "languages": ["en"], "tld": ".jm", "is_eu": False, "is_eea": False, "timezone": "America/Jamaica"},
    "JO": {"alpha3": "JOR", "numeric": "400", "continent": "Asia", "region": "Western Asia", "capital": "Amman", "currency_code": "JOD", "currency_name": "Jordanian Dinar", "currency_symbol": "JD", "languages": ["ar"], "tld": ".jo", "is_eu": False, "is_eea": False, "timezone": "Asia/Amman"},
    "JP": {"alpha3": "JPN", "numeric": "392", "continent": "Asia", "region": "Eastern Asia", "capital": "Tokyo", "currency_code": "JPY", "currency_name": "Japanese Yen", "currency_symbol": "¥", "languages": ["ja"], "tld": ".jp", "is_eu": False, "is_eea": False, "timezone": "Asia/Tokyo"},
    "KE": {"alpha3": "KEN", "numeric": "404", "continent": "Africa", "region": "Eastern Africa", "capital": "Nairobi", "currency_code": "KES", "currency_name": "Kenyan Shilling", "currency_symbol": "KSh", "languages": ["en", "sw"], "tld": ".ke", "is_eu": False, "is_eea": False, "timezone": "Africa/Nairobi"},
    "KG": {"alpha3": "KGZ", "numeric": "417", "continent": "Asia", "region": "Central Asia", "capital": "Bishkek", "currency_code": "KGS", "currency_name": "Kyrgystani Som", "currency_symbol": "с", "languages": ["ky", "ru"], "tld": ".kg", "is_eu": False, "is_eea": False, "timezone": "Asia/Bishkek"},
    "KH": {"alpha3": "KHM", "numeric": "116", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Phnom Penh", "currency_code": "KHR", "currency_name": "Cambodian Riel", "currency_symbol": "៛", "languages": ["km"], "tld": ".kh", "is_eu": False, "is_eea": False, "timezone": "Asia/Phnom_Penh"},
    "KI": {"alpha3": "KIR", "numeric": "296", "continent": "Oceania", "region": "Micronesia", "capital": "Tarawa", "currency_code": "AUD", "currency_name": "Australian Dollar", "currency_symbol": "A$", "languages": ["en"], "tld": ".ki", "is_eu": False, "is_eea": False, "timezone": "Pacific/Tarawa"},
    "KM": {"alpha3": "COM", "numeric": "174", "continent": "Africa", "region": "Eastern Africa", "capital": "Moroni", "currency_code": "KMF", "currency_name": "Comorian Franc", "currency_symbol": "Fr", "languages": ["ar", "fr"], "tld": ".km", "is_eu": False, "is_eea": False, "timezone": "Indian/Comoro"},
    "KN": {"alpha3": "KNA", "numeric": "659", "continent": "North America", "region": "Caribbean", "capital": "Basseterre", "currency_code": "XCD", "currency_name": "East Caribbean Dollar", "currency_symbol": "EC$", "languages": ["en"], "tld": ".kn", "is_eu": False, "is_eea": False, "timezone": "America/St_Kitts"},
    "KP": {"alpha3": "PRK", "numeric": "408", "continent": "Asia", "region": "Eastern Asia", "capital": "Pyongyang", "currency_code": "KPW", "currency_name": "North Korean Won", "currency_symbol": "₩", "languages": ["ko"], "tld": ".kp", "is_eu": False, "is_eea": False, "timezone": "Asia/Pyongyang"},
    "KR": {"alpha3": "KOR", "numeric": "410", "continent": "Asia", "region": "Eastern Asia", "capital": "Seoul", "currency_code": "KRW", "currency_name": "South Korean Won", "currency_symbol": "₩", "languages": ["ko"], "tld": ".kr", "is_eu": False, "is_eea": False, "timezone": "Asia/Seoul"},
    "KW": {"alpha3": "KWT", "numeric": "414", "continent": "Asia", "region": "Western Asia", "capital": "Kuwait City", "currency_code": "KWD", "currency_name": "Kuwaiti Dinar", "currency_symbol": "KD", "languages": ["ar"], "tld": ".kw", "is_eu": False, "is_eea": False, "timezone": "Asia/Kuwait"},
    "KY": {"alpha3": "CYM", "numeric": "136", "continent": "North America", "region": "Caribbean", "capital": "George Town", "currency_code": "KYD", "currency_name": "Cayman Islands Dollar", "currency_symbol": "CI$", "languages": ["en"], "tld": ".ky", "is_eu": False, "is_eea": False, "timezone": "America/Cayman"},
    "KZ": {"alpha3": "KAZ", "numeric": "398", "continent": "Asia", "region": "Central Asia", "capital": "Astana", "currency_code": "KZT", "currency_name": "Kazakhstani Tenge", "currency_symbol": "₸", "languages": ["kk", "ru"], "tld": ".kz", "is_eu": False, "is_eea": False, "timezone": "Asia/Almaty"},
    "LA": {"alpha3": "LAO", "numeric": "418", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Vientiane", "currency_code": "LAK", "currency_name": "Laotian Kip", "currency_symbol": "₭", "languages": ["lo"], "tld": ".la", "is_eu": False, "is_eea": False, "timezone": "Asia/Vientiane"},
    "LB": {"alpha3": "LBN", "numeric": "422", "continent": "Asia", "region": "Western Asia", "capital": "Beirut", "currency_code": "LBP", "currency_name": "Lebanese Pound", "currency_symbol": "ل.ل", "languages": ["ar", "fr"], "tld": ".lb", "is_eu": False, "is_eea": False, "timezone": "Asia/Beirut"},
    "LC": {"alpha3": "LCA", "numeric": "662", "continent": "North America", "region": "Caribbean", "capital": "Castries", "currency_code": "XCD", "currency_name": "East Caribbean Dollar", "currency_symbol": "EC$", "languages": ["en"], "tld": ".lc", "is_eu": False, "is_eea": False, "timezone": "America/St_Lucia"},
    "LI": {"alpha3": "LIE", "numeric": "438", "continent": "Europe", "region": "Western Europe", "capital": "Vaduz", "currency_code": "CHF", "currency_name": "Swiss Franc", "currency_symbol": "CHF", "languages": ["de"], "tld": ".li", "is_eu": False, "is_eea": True, "timezone": "Europe/Vaduz"},
    "LK": {"alpha3": "LKA", "numeric": "144", "continent": "Asia", "region": "Southern Asia", "capital": "Colombo", "currency_code": "LKR", "currency_name": "Sri Lankan Rupee", "currency_symbol": "LKR", "languages": ["si", "ta"], "tld": ".lk", "is_eu": False, "is_eea": False, "timezone": "Asia/Colombo"},
    "LR": {"alpha3": "LBR", "numeric": "430", "continent": "Africa", "region": "Western Africa", "capital": "Monrovia", "currency_code": "LRD", "currency_name": "Liberian Dollar", "currency_symbol": "L$", "languages": ["en"], "tld": ".lr", "is_eu": False, "is_eea": False, "timezone": "Africa/Monrovia"},
    "LS": {"alpha3": "LSO", "numeric": "426", "continent": "Africa", "region": "Southern Africa", "capital": "Maseru", "currency_code": "LSL", "currency_name": "Lesotho Loti", "currency_symbol": "M", "languages": ["en", "st"], "tld": ".ls", "is_eu": False, "is_eea": False, "timezone": "Africa/Maseru"},
    "LT": {"alpha3": "LTU", "numeric": "440", "continent": "Europe", "region": "Northern Europe", "capital": "Vilnius", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["lt"], "tld": ".lt", "is_eu": True, "is_eea": True, "timezone": "Europe/Vilnius"},
    "LU": {"alpha3": "LUX", "numeric": "442", "continent": "Europe", "region": "Western Europe", "capital": "Luxembourg", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr", "de", "lb"], "tld": ".lu", "is_eu": True, "is_eea": True, "timezone": "Europe/Luxembourg"},
    "LV": {"alpha3": "LVA", "numeric": "428", "continent": "Europe", "region": "Northern Europe", "capital": "Riga", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["lv"], "tld": ".lv", "is_eu": True, "is_eea": True, "timezone": "Europe/Riga"},
    "LY": {"alpha3": "LBY", "numeric": "434", "continent": "Africa", "region": "Northern Africa", "capital": "Tripoli", "currency_code": "LYD", "currency_name": "Libyan Dinar", "currency_symbol": "LD", "languages": ["ar"], "tld": ".ly", "is_eu": False, "is_eea": False, "timezone": "Africa/Tripoli"},
    "MA": {"alpha3": "MAR", "numeric": "504", "continent": "Africa", "region": "Northern Africa", "capital": "Rabat", "currency_code": "MAD", "currency_name": "Moroccan Dirham", "currency_symbol": "MAD", "languages": ["ar"], "tld": ".ma", "is_eu": False, "is_eea": False, "timezone": "Africa/Casablanca"},
    "MC": {"alpha3": "MCO", "numeric": "492", "continent": "Europe", "region": "Western Europe", "capital": "Monaco", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".mc", "is_eu": False, "is_eea": False, "timezone": "Europe/Monaco"},
    "MD": {"alpha3": "MDA", "numeric": "498", "continent": "Europe", "region": "Eastern Europe", "capital": "Chisinau", "currency_code": "MDL", "currency_name": "Moldovan Leu", "currency_symbol": "L", "languages": ["ro"], "tld": ".md", "is_eu": False, "is_eea": False, "timezone": "Europe/Chisinau"},
    "ME": {"alpha3": "MNE", "numeric": "499", "continent": "Europe", "region": "Southern Europe", "capital": "Podgorica", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["sr"], "tld": ".me", "is_eu": False, "is_eea": False, "timezone": "Europe/Podgorica"},
    "MF": {"alpha3": "MAF", "numeric": "663", "continent": "North America", "region": "Caribbean", "capital": "Marigot", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".mf", "is_eu": False, "is_eea": False, "timezone": "America/Marigot"},
    "MG": {"alpha3": "MDG", "numeric": "450", "continent": "Africa", "region": "Eastern Africa", "capital": "Antananarivo", "currency_code": "MGA", "currency_name": "Malagasy Ariary", "currency_symbol": "Ar", "languages": ["fr", "mg"], "tld": ".mg", "is_eu": False, "is_eea": False, "timezone": "Indian/Antananarivo"},
    "MH": {"alpha3": "MHL", "numeric": "584", "continent": "Oceania", "region": "Micronesia", "capital": "Majuro", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en", "mh"], "tld": ".mh", "is_eu": False, "is_eea": False, "timezone": "Pacific/Majuro"},
    "MK": {"alpha3": "MKD", "numeric": "807", "continent": "Europe", "region": "Southern Europe", "capital": "Skopje", "currency_code": "MKD", "currency_name": "Macedonian Denar", "currency_symbol": "ден", "languages": ["mk"], "tld": ".mk", "is_eu": False, "is_eea": False, "timezone": "Europe/Skopje"},
    "ML": {"alpha3": "MLI", "numeric": "466", "continent": "Africa", "region": "Western Africa", "capital": "Bamako", "currency_code": "XOF", "currency_name": "West African CFA Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".ml", "is_eu": False, "is_eea": False, "timezone": "Africa/Bamako"},
    "MM": {"alpha3": "MMR", "numeric": "104", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Naypyidaw", "currency_code": "MMK", "currency_name": "Myanma Kyat", "currency_symbol": "K", "languages": ["my"], "tld": ".mm", "is_eu": False, "is_eea": False, "timezone": "Asia/Rangoon"},
    "MN": {"alpha3": "MNG", "numeric": "496", "continent": "Asia", "region": "Eastern Asia", "capital": "Ulaanbaatar", "currency_code": "MNT", "currency_name": "Mongolian Tugrik", "currency_symbol": "₮", "languages": ["mn"], "tld": ".mn", "is_eu": False, "is_eea": False, "timezone": "Asia/Ulaanbaatar"},
    "MO": {"alpha3": "MAC", "numeric": "446", "continent": "Asia", "region": "Eastern Asia", "capital": "Macao", "currency_code": "MOP", "currency_name": "Macanese Pataca", "currency_symbol": "P", "languages": ["zh", "pt"], "tld": ".mo", "is_eu": False, "is_eea": False, "timezone": "Asia/Macau"},
    "MP": {"alpha3": "MNP", "numeric": "580", "continent": "Oceania", "region": "Micronesia", "capital": "Saipan", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en", "ch"], "tld": ".mp", "is_eu": False, "is_eea": False, "timezone": "Pacific/Saipan"},
    "MQ": {"alpha3": "MTQ", "numeric": "474", "continent": "North America", "region": "Caribbean", "capital": "Fort-de-France", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".mq", "is_eu": False, "is_eea": False, "timezone": "America/Martinique"},
    "MR": {"alpha3": "MRT", "numeric": "478", "continent": "Africa", "region": "Western Africa", "capital": "Nouakchott", "currency_code": "MRO", "currency_name": "Mauritanian Ouguiya", "currency_symbol": "UM", "languages": ["ar"], "tld": ".mr", "is_eu": False, "is_eea": False, "timezone": "Africa/Nouakchott"},
    "MS": {"alpha3": "MSR", "numeric": "500", "continent": "North America", "region": "Caribbean", "capital": "Plymouth", "currency_code": "XCD", "currency_name": "East Caribbean Dollar", "currency_symbol": "EC$", "languages": ["en"], "tld": ".ms", "is_eu": False, "is_eea": False, "timezone": "America/Montserrat"},
    "MT": {"alpha3": "MLT", "numeric": "470", "continent": "Europe", "region": "Southern Europe", "capital": "Valletta", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["mt", "en"], "tld": ".mt", "is_eu": True, "is_eea": True, "timezone": "Europe/Malta"},
    "MU": {"alpha3": "MUS", "numeric": "480", "continent": "Africa", "region": "Eastern Africa", "capital": "Port Louis", "currency_code": "MUR", "currency_name": "Mauritian Rupee", "currency_symbol": "₨", "languages": ["en"], "tld": ".mu", "is_eu": False, "is_eea": False, "timezone": "Indian/Mauritius"},
    "MV": {"alpha3": "MDV", "numeric": "462", "continent": "Asia", "region": "Southern Asia", "capital": "Male", "currency_code": "MVR", "currency_name": "Maldivian Rufiyaa", "currency_symbol": "Rf", "languages": ["dv"], "tld": ".mv", "is_eu": False, "is_eea": False, "timezone": "Indian/Maldives"},
    "MW": {"alpha3": "MWI", "numeric": "454", "continent": "Africa", "region": "Eastern Africa", "capital": "Lilongwe", "currency_code": "MWK", "currency_name": "Malawian Kwacha", "currency_symbol": "MK", "languages": ["en", "ny"], "tld": ".mw", "is_eu": False, "is_eea": False, "timezone": "Africa/Blantyre"},
    "MX": {"alpha3": "MEX", "numeric": "484", "continent": "North America", "region": "Central America", "capital": "Mexico City", "currency_code": "MXN", "currency_name": "Mexican Peso", "currency_symbol": "$", "languages": ["es"], "tld": ".mx", "is_eu": False, "is_eea": False, "timezone": "America/Mexico_City"},
    "MY": {"alpha3": "MYS", "numeric": "458", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Kuala Lumpur", "currency_code": "MYR", "currency_name": "Malaysian Ringgit", "currency_symbol": "RM", "languages": ["ms"], "tld": ".my", "is_eu": False, "is_eea": False, "timezone": "Asia/Kuala_Lumpur"},
    "MZ": {"alpha3": "MOZ", "numeric": "508", "continent": "Africa", "region": "Eastern Africa", "capital": "Maputo", "currency_code": "MZN", "currency_name": "Mozambican Metical", "currency_symbol": "MT", "languages": ["pt"], "tld": ".mz", "is_eu": False, "is_eea": False, "timezone": "Africa/Maputo"},
    "NA": {"alpha3": "NAM", "numeric": "516", "continent": "Africa", "region": "Southern Africa", "capital": "Windhoek", "currency_code": "NAD", "currency_name": "Namibian Dollar", "currency_symbol": "N$", "languages": ["en", "af"], "tld": ".na", "is_eu": False, "is_eea": False, "timezone": "Africa/Windhoek"},
    "NC": {"alpha3": "NCL", "numeric": "540", "continent": "Oceania", "region": "Melanesia", "capital": "Noumea", "currency_code": "XPF", "currency_name": "CFP Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".nc", "is_eu": False, "is_eea": False, "timezone": "Pacific/Noumea"},
    "NE": {"alpha3": "NER", "numeric": "562", "continent": "Africa", "region": "Western Africa", "capital": "Niamey", "currency_code": "XOF", "currency_name": "West African CFA Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".ne", "is_eu": False, "is_eea": False, "timezone": "Africa/Niamey"},
    "NF": {"alpha3": "NFK", "numeric": "574", "continent": "Oceania", "region": "Australia and New Zealand", "capital": "Kingston", "currency_code": "AUD", "currency_name": "Australian Dollar", "currency_symbol": "A$", "languages": ["en"], "tld": ".nf", "is_eu": False, "is_eea": False, "timezone": "Pacific/Norfolk"},
    "NG": {"alpha3": "NGA", "numeric": "566", "continent": "Africa", "region": "Western Africa", "capital": "Abuja", "currency_code": "NGN", "currency_name": "Nigerian Naira", "currency_symbol": "₦", "languages": ["en"], "tld": ".ng", "is_eu": False, "is_eea": False, "timezone": "Africa/Lagos"},
    "NI": {"alpha3": "NIC", "numeric": "558", "continent": "North America", "region": "Central America", "capital": "Managua", "currency_code": "NIO", "currency_name": "Nicaraguan Cordoba", "currency_symbol": "C$", "languages": ["es"], "tld": ".ni", "is_eu": False, "is_eea": False, "timezone": "America/Managua"},
    "NL": {"alpha3": "NLD", "numeric": "528", "continent": "Europe", "region": "Western Europe", "capital": "Amsterdam", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["nl"], "tld": ".nl", "is_eu": True, "is_eea": True, "timezone": "Europe/Amsterdam"},
    "NO": {"alpha3": "NOR", "numeric": "578", "continent": "Europe", "region": "Northern Europe", "capital": "Oslo", "currency_code": "NOK", "currency_name": "Norwegian Krone", "currency_symbol": "kr", "languages": ["no", "nb", "nn"], "tld": ".no", "is_eu": False, "is_eea": True, "timezone": "Europe/Oslo"},
    "NP": {"alpha3": "NPL", "numeric": "524", "continent": "Asia", "region": "Southern Asia", "capital": "Kathmandu", "currency_code": "NPR", "currency_name": "Nepalese Rupee", "currency_symbol": "₨", "languages": ["ne"], "tld": ".np", "is_eu": False, "is_eea": False, "timezone": "Asia/Kathmandu"},
    "NR": {"alpha3": "NRU", "numeric": "520", "continent": "Oceania", "region": "Micronesia", "capital": "Yaren", "currency_code": "AUD", "currency_name": "Australian Dollar", "currency_symbol": "A$", "languages": ["en", "na"], "tld": ".nr", "is_eu": False, "is_eea": False, "timezone": "Pacific/Nauru"},
    "NU": {"alpha3": "NIU", "numeric": "570", "continent": "Oceania", "region": "Polynesia", "capital": "Alofi", "currency_code": "NZD", "currency_name": "New Zealand Dollar", "currency_symbol": "NZ$", "languages": ["en"], "tld": ".nu", "is_eu": False, "is_eea": False, "timezone": "Pacific/Niue"},
    "NZ": {"alpha3": "NZL", "numeric": "554", "continent": "Oceania", "region": "Australia and New Zealand", "capital": "Wellington", "currency_code": "NZD", "currency_name": "New Zealand Dollar", "currency_symbol": "NZ$", "languages": ["en", "mi"], "tld": ".nz", "is_eu": False, "is_eea": False, "timezone": "Pacific/Auckland"},
    "OM": {"alpha3": "OMN", "numeric": "512", "continent": "Asia", "region": "Western Asia", "capital": "Muscat", "currency_code": "OMR", "currency_name": "Omani Rial", "currency_symbol": "﷼", "languages": ["ar"], "tld": ".om", "is_eu": False, "is_eea": False, "timezone": "Asia/Muscat"},
    "PA": {"alpha3": "PAN", "numeric": "591", "continent": "North America", "region": "Central America", "capital": "Panama City", "currency_code": "PAB", "currency_name": "Panamanian Balboa", "currency_symbol": "B/.", "languages": ["es"], "tld": ".pa", "is_eu": False, "is_eea": False, "timezone": "America/Panama"},
    "PE": {"alpha3": "PER", "numeric": "604", "continent": "South America", "region": "South America", "capital": "Lima", "currency_code": "PEN", "currency_name": "Peruvian Nuevo Sol", "currency_symbol": "S/.", "languages": ["es"], "tld": ".pe", "is_eu": False, "is_eea": False, "timezone": "America/Lima"},
    "PF": {"alpha3": "PYF", "numeric": "258", "continent": "Oceania", "region": "Polynesia", "capital": "Papeete", "currency_code": "XPF", "currency_name": "CFP Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".pf", "is_eu": False, "is_eea": False, "timezone": "Pacific/Tahiti"},
    "PG": {"alpha3": "PNG", "numeric": "598", "continent": "Oceania", "region": "Melanesia", "capital": "Port Moresby", "currency_code": "PGK", "currency_name": "Papua New Guinean Kina", "currency_symbol": "K", "languages": ["en"], "tld": ".pg", "is_eu": False, "is_eea": False, "timezone": "Pacific/Port_Moresby"},
    "PH": {"alpha3": "PHL", "numeric": "608", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Manila", "currency_code": "PHP", "currency_name": "Philippine Peso", "currency_symbol": "₱", "languages": ["fil", "en"], "tld": ".ph", "is_eu": False, "is_eea": False, "timezone": "Asia/Manila"},
    "PK": {"alpha3": "PAK", "numeric": "586", "continent": "Asia", "region": "Southern Asia", "capital": "Islamabad", "currency_code": "PKR", "currency_name": "Pakistani Rupee", "currency_symbol": "₨", "languages": ["en", "ur"], "tld": ".pk", "is_eu": False, "is_eea": False, "timezone": "Asia/Karachi"},
    "PL": {"alpha3": "POL", "numeric": "616", "continent": "Europe", "region": "Eastern Europe", "capital": "Warsaw", "currency_code": "PLN", "currency_name": "Polish Zloty", "currency_symbol": "zł", "languages": ["pl"], "tld": ".pl", "is_eu": True, "is_eea": True, "timezone": "Europe/Warsaw"},
    "PM": {"alpha3": "SPM", "numeric": "666", "continent": "North America", "region": "Northern America", "capital": "Saint-Pierre", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".pm", "is_eu": False, "is_eea": False, "timezone": "America/Miquelon"},
    "PN": {"alpha3": "PCN", "numeric": "612", "continent": "Oceania", "region": "Polynesia", "capital": "Adamstown", "currency_code": "NZD", "currency_name": "New Zealand Dollar", "currency_symbol": "NZ$", "languages": ["en"], "tld": ".pn", "is_eu": False, "is_eea": False, "timezone": "Pacific/Pitcairn"},
    "PR": {"alpha3": "PRI", "numeric": "630", "continent": "North America", "region": "Caribbean", "capital": "San Juan", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["es", "en"], "tld": ".pr", "is_eu": False, "is_eea": False, "timezone": "America/Puerto_Rico"},
    "PS": {"alpha3": "PSE", "numeric": "275", "continent": "Asia", "region": "Western Asia", "capital": "Ramallah", "currency_code": "ILS", "currency_name": "Israeli New Shekel", "currency_symbol": "₪", "languages": ["ar"], "tld": ".ps", "is_eu": False, "is_eea": False, "timezone": "Asia/Gaza"},
    "PT": {"alpha3": "PRT", "numeric": "620", "continent": "Europe", "region": "Southern Europe", "capital": "Lisbon", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["pt"], "tld": ".pt", "is_eu": True, "is_eea": True, "timezone": "Europe/Lisbon"},
    "PW": {"alpha3": "PLW", "numeric": "585", "continent": "Oceania", "region": "Micronesia", "capital": "Ngerulmud", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".pw", "is_eu": False, "is_eea": False, "timezone": "Pacific/Palau"},
    "PY": {"alpha3": "PRY", "numeric": "600", "continent": "South America", "region": "South America", "capital": "Asuncion", "currency_code": "PYG", "currency_name": "Paraguayan Guarani", "currency_symbol": "₲", "languages": ["es", "gn"], "tld": ".py", "is_eu": False, "is_eea": False, "timezone": "America/Asuncion"},
    "QA": {"alpha3": "QAT", "numeric": "634", "continent": "Asia", "region": "Western Asia", "capital": "Doha", "currency_code": "QAR", "currency_name": "Qatari Rial", "currency_symbol": "﷼", "languages": ["ar"], "tld": ".qa", "is_eu": False, "is_eea": False, "timezone": "Asia/Qatar"},
    "RE": {"alpha3": "REU", "numeric": "638", "continent": "Africa", "region": "Eastern Africa", "capital": "Saint-Denis", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".re", "is_eu": False, "is_eea": False, "timezone": "Indian/Reunion"},
    "RO": {"alpha3": "ROU", "numeric": "642", "continent": "Europe", "region": "Eastern Europe", "capital": "Bucharest", "currency_code": "RON", "currency_name": "Romanian Leu", "currency_symbol": "lei", "languages": ["ro"], "tld": ".ro", "is_eu": True, "is_eea": True, "timezone": "Europe/Bucharest"},
    "RS": {"alpha3": "SRB", "numeric": "688", "continent": "Europe", "region": "Southern Europe", "capital": "Belgrade", "currency_code": "RSD", "currency_name": "Serbian Dinar", "currency_symbol": "din", "languages": ["sr"], "tld": ".rs", "is_eu": False, "is_eea": False, "timezone": "Europe/Belgrade"},
    "RU": {"alpha3": "RUS", "numeric": "643", "continent": "Europe", "region": "Eastern Europe", "capital": "Moscow", "currency_code": "RUB", "currency_name": "Russian Ruble", "currency_symbol": "₽", "languages": ["ru"], "tld": ".ru", "is_eu": False, "is_eea": False, "timezone": "Europe/Moscow"},
    "RW": {"alpha3": "RWA", "numeric": "646", "continent": "Africa", "region": "Eastern Africa", "capital": "Kigali", "currency_code": "RWF", "currency_name": "Rwandan Franc", "currency_symbol": "Fr", "languages": ["rw", "en", "fr"], "tld": ".rw", "is_eu": False, "is_eea": False, "timezone": "Africa/Kigali"},
    "SA": {"alpha3": "SAU", "numeric": "682", "continent": "Asia", "region": "Western Asia", "capital": "Riyadh", "currency_code": "SAR", "currency_name": "Saudi Riyal", "currency_symbol": "﷼", "languages": ["ar"], "tld": ".sa", "is_eu": False, "is_eea": False, "timezone": "Asia/Riyadh"},
    "SB": {"alpha3": "SLB", "numeric": "090", "continent": "Oceania", "region": "Melanesia", "capital": "Honiara", "currency_code": "SBD", "currency_name": "Solomon Islands Dollar", "currency_symbol": "SI$", "languages": ["en"], "tld": ".sb", "is_eu": False, "is_eea": False, "timezone": "Pacific/Guadalcanal"},
    "SC": {"alpha3": "SYC", "numeric": "690", "continent": "Africa", "region": "Eastern Africa", "capital": "Victoria", "currency_code": "SCR", "currency_name": "Seychellois Rupee", "currency_symbol": "₨", "languages": ["fr", "en"], "tld": ".sc", "is_eu": False, "is_eea": False, "timezone": "Indian/Mahe"},
    "SD": {"alpha3": "SDN", "numeric": "729", "continent": "Africa", "region": "Northern Africa", "capital": "Khartoum", "currency_code": "SDG", "currency_name": "Sudanese Pound", "currency_symbol": "£", "languages": ["ar", "en"], "tld": ".sd", "is_eu": False, "is_eea": False, "timezone": "Africa/Khartoum"},
    "SE": {"alpha3": "SWE", "numeric": "752", "continent": "Europe", "region": "Northern Europe", "capital": "Stockholm", "currency_code": "SEK", "currency_name": "Swedish Krona", "currency_symbol": "kr", "languages": ["sv"], "tld": ".se", "is_eu": True, "is_eea": True, "timezone": "Europe/Stockholm"},
    "SG": {"alpha3": "SGP", "numeric": "702", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Singapore", "currency_code": "SGD", "currency_name": "Singapore Dollar", "currency_symbol": "S$", "languages": ["en", "ms", "ta", "zh"], "tld": ".sg", "is_eu": False, "is_eea": False, "timezone": "Asia/Singapore"},
    "SH": {"alpha3": "SHN", "numeric": "654", "continent": "Africa", "region": "Western Africa", "capital": "Jamestown", "currency_code": "SHP", "currency_name": "Saint Helenian Pound", "currency_symbol": "£", "languages": ["en"], "tld": ".sh", "is_eu": False, "is_eea": False, "timezone": "Atlantic/St_Helena"},
    "SI": {"alpha3": "SVN", "numeric": "705", "continent": "Europe", "region": "Southern Europe", "capital": "Ljubljana", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["sl"], "tld": ".si", "is_eu": True, "is_eea": True, "timezone": "Europe/Ljubljana"},
    "SJ": {"alpha3": "SJM", "numeric": "744", "continent": "Europe", "region": "Northern Europe", "capital": "Longyearbyen", "currency_code": "NOK", "currency_name": "Norwegian Krone", "currency_symbol": "kr", "languages": ["no"], "tld": ".sj", "is_eu": False, "is_eea": False, "timezone": "Arctic/Longyearbyen"},
    "SK": {"alpha3": "SVK", "numeric": "703", "continent": "Europe", "region": "Eastern Europe", "capital": "Bratislava", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["sk"], "tld": ".sk", "is_eu": True, "is_eea": True, "timezone": "Europe/Bratislava"},
    "SL": {"alpha3": "SLE", "numeric": "694", "continent": "Africa", "region": "Western Africa", "capital": "Freetown", "currency_code": "SLL", "currency_name": "Sierra Leonean Leone", "currency_symbol": "Le", "languages": ["en"], "tld": ".sl", "is_eu": False, "is_eea": False, "timezone": "Africa/Freetown"},
    "SM": {"alpha3": "SMR", "numeric": "674", "continent": "Europe", "region": "Southern Europe", "capital": "San Marino", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["it"], "tld": ".sm", "is_eu": False, "is_eea": False, "timezone": "Europe/San_Marino"},
    "SN": {"alpha3": "SEN", "numeric": "686", "continent": "Africa", "region": "Western Africa", "capital": "Dakar", "currency_code": "XOF", "currency_name": "West African CFA Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".sn", "is_eu": False, "is_eea": False, "timezone": "Africa/Dakar"},
    "SO": {"alpha3": "SOM", "numeric": "706", "continent": "Africa", "region": "Eastern Africa", "capital": "Mogadishu", "currency_code": "SOS", "currency_name": "Somali Shilling", "currency_symbol": "Sh", "languages": ["so", "ar"], "tld": ".so", "is_eu": False, "is_eea": False, "timezone": "Africa/Mogadishu"},
    "SR": {"alpha3": "SUR", "numeric": "740", "continent": "South America", "region": "South America", "capital": "Paramaribo", "currency_code": "SRD", "currency_name": "Surinamese Dollar", "currency_symbol": "$", "languages": ["nl"], "tld": ".sr", "is_eu": False, "is_eea": False, "timezone": "America/Paramaribo"},
    "SS": {"alpha3": "SSD", "numeric": "728", "continent": "Africa", "region": "Eastern Africa", "capital": "Juba", "currency_code": "SSP", "currency_name": "South Sudanese Pound", "currency_symbol": "£", "languages": ["en"], "tld": ".ss", "is_eu": False, "is_eea": False, "timezone": "Africa/Juba"},
    "ST": {"alpha3": "STP", "numeric": "678", "continent": "Africa", "region": "Middle Africa", "capital": "Sao Tome", "currency_code": "STD", "currency_name": "Sao Tomean Dobra", "currency_symbol": "Db", "languages": ["pt"], "tld": ".st", "is_eu": False, "is_eea": False, "timezone": "Africa/Sao_Tome"},
    "SV": {"alpha3": "SLV", "numeric": "222", "continent": "North America", "region": "Central America", "capital": "San Salvador", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["es"], "tld": ".sv", "is_eu": False, "is_eea": False, "timezone": "America/El_Salvador"},
    "SX": {"alpha3": "SXM", "numeric": "534", "continent": "North America", "region": "Caribbean", "capital": "Philipsburg", "currency_code": "ANG", "currency_name": "Netherlands Antillean Guilder", "currency_symbol": "ƒ", "languages": ["nl", "en"], "tld": ".sx", "is_eu": False, "is_eea": False, "timezone": "America/Lower_Princes"},
    "SY": {"alpha3": "SYR", "numeric": "760", "continent": "Asia", "region": "Western Asia", "capital": "Damascus", "currency_code": "SYP", "currency_name": "Syrian Pound", "currency_symbol": "£", "languages": ["ar"], "tld": ".sy", "is_eu": False, "is_eea": False, "timezone": "Asia/Damascus"},
    "SZ": {"alpha3": "SWZ", "numeric": "748", "continent": "Africa", "region": "Southern Africa", "capital": "Mbabane", "currency_code": "SZL", "currency_name": "Swazi Lilangeni", "currency_symbol": "L", "languages": ["en", "ss"], "tld": ".sz", "is_eu": False, "is_eea": False, "timezone": "Africa/Mbabane"},
    "TC": {"alpha3": "TCA", "numeric": "796", "continent": "North America", "region": "Caribbean", "capital": "Cockburn Town", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".tc", "is_eu": False, "is_eea": False, "timezone": "America/Grand_Turk"},
    "TD": {"alpha3": "TCD", "numeric": "148", "continent": "Africa", "region": "Middle Africa", "capital": "N'Djamena", "currency_code": "XAF", "currency_name": "Central African CFA Franc", "currency_symbol": "Fr", "languages": ["fr", "ar"], "tld": ".td", "is_eu": False, "is_eea": False, "timezone": "Africa/Ndjamena"},
    "TF": {"alpha3": "ATF", "numeric": "260", "continent": "Antarctica", "region": "Antarctica", "capital": "Port-aux-Francais", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".tf", "is_eu": False, "is_eea": False, "timezone": "Indian/Kerguelen"},
    "TG": {"alpha3": "TGO", "numeric": "768", "continent": "Africa", "region": "Western Africa", "capital": "Lome", "currency_code": "XOF", "currency_name": "West African CFA Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".tg", "is_eu": False, "is_eea": False, "timezone": "Africa/Lome"},
    "TH": {"alpha3": "THA", "numeric": "764", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Bangkok", "currency_code": "THB", "currency_name": "Thai Baht", "currency_symbol": "฿", "languages": ["th"], "tld": ".th", "is_eu": False, "is_eea": False, "timezone": "Asia/Bangkok"},
    "TJ": {"alpha3": "TJK", "numeric": "762", "continent": "Asia", "region": "Central Asia", "capital": "Dushanbe", "currency_code": "TJS", "currency_name": "Tajikistani Somoni", "currency_symbol": "SM", "languages": ["tg", "ru"], "tld": ".tj", "is_eu": False, "is_eea": False, "timezone": "Asia/Dushanbe"},
    "TK": {"alpha3": "TKL", "numeric": "772", "continent": "Oceania", "region": "Polynesia", "capital": "Fakaofo", "currency_code": "NZD", "currency_name": "New Zealand Dollar", "currency_symbol": "NZ$", "languages": ["en"], "tld": ".tk", "is_eu": False, "is_eea": False, "timezone": "Pacific/Fakaofo"},
    "TL": {"alpha3": "TLS", "numeric": "626", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Dili", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["pt", "tet"], "tld": ".tl", "is_eu": False, "is_eea": False, "timezone": "Asia/Dili"},
    "TM": {"alpha3": "TKM", "numeric": "795", "continent": "Asia", "region": "Central Asia", "capital": "Ashgabat", "currency_code": "TMT", "currency_name": "Turkmenistani Manat", "currency_symbol": "T", "languages": ["tk", "ru"], "tld": ".tm", "is_eu": False, "is_eea": False, "timezone": "Asia/Ashgabat"},
    "TN": {"alpha3": "TUN", "numeric": "788", "continent": "Africa", "region": "Northern Africa", "capital": "Tunis", "currency_code": "TND", "currency_name": "Tunisian Dinar", "currency_symbol": "DT", "languages": ["ar"], "tld": ".tn", "is_eu": False, "is_eea": False, "timezone": "Africa/Tunis"},
    "TO": {"alpha3": "TON", "numeric": "776", "continent": "Oceania", "region": "Polynesia", "capital": "Nuku'alofa", "currency_code": "TOP", "currency_name": "Tongan Pa'anga", "currency_symbol": "T$", "languages": ["to", "en"], "tld": ".to", "is_eu": False, "is_eea": False, "timezone": "Pacific/Tongatapu"},
    "TR": {"alpha3": "TUR", "numeric": "792", "continent": "Asia", "region": "Western Asia", "capital": "Ankara", "currency_code": "TRY", "currency_name": "Turkish Lira", "currency_symbol": "₺", "languages": ["tr"], "tld": ".tr", "is_eu": False, "is_eea": False, "timezone": "Europe/Istanbul"},
    "TT": {"alpha3": "TTO", "numeric": "780", "continent": "North America", "region": "Caribbean", "capital": "Port of Spain", "currency_code": "TTD", "currency_name": "Trinidad and Tobago Dollar", "currency_symbol": "TT$", "languages": ["en"], "tld": ".tt", "is_eu": False, "is_eea": False, "timezone": "America/Port_of_Spain"},
    "TV": {"alpha3": "TUV", "numeric": "798", "continent": "Oceania", "region": "Polynesia", "capital": "Funafuti", "currency_code": "AUD", "currency_name": "Australian Dollar", "currency_symbol": "A$", "languages": ["en"], "tld": ".tv", "is_eu": False, "is_eea": False, "timezone": "Pacific/Funafuti"},
    "TW": {"alpha3": "TWN", "numeric": "158", "continent": "Asia", "region": "Eastern Asia", "capital": "Taipei", "currency_code": "TWD", "currency_name": "New Taiwan Dollar", "currency_symbol": "NT$", "languages": ["zh"], "tld": ".tw", "is_eu": False, "is_eea": False, "timezone": "Asia/Taipei"},
    "TZ": {"alpha3": "TZA", "numeric": "834", "continent": "Africa", "region": "Eastern Africa", "capital": "Dodoma", "currency_code": "TZS", "currency_name": "Tanzanian Shilling", "currency_symbol": "Sh", "languages": ["sw", "en"], "tld": ".tz", "is_eu": False, "is_eea": False, "timezone": "Africa/Dar_es_Salaam"},
    "UA": {"alpha3": "UKR", "numeric": "804", "continent": "Europe", "region": "Eastern Europe", "capital": "Kyiv", "currency_code": "UAH", "currency_name": "Ukrainian Hryvnia", "currency_symbol": "₴", "languages": ["uk"], "tld": ".ua", "is_eu": False, "is_eea": False, "timezone": "Europe/Kiev"},
    "UG": {"alpha3": "UGA", "numeric": "800", "continent": "Africa", "region": "Eastern Africa", "capital": "Kampala", "currency_code": "UGX", "currency_name": "Ugandan Shilling", "currency_symbol": "Sh", "languages": ["en", "sw"], "tld": ".ug", "is_eu": False, "is_eea": False, "timezone": "Africa/Kampala"},
    "UM": {"alpha3": "UMI", "numeric": "581", "continent": "Oceania", "region": "Micronesia", "capital": "", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".um", "is_eu": False, "is_eea": False, "timezone": "Pacific/Johnston"},
    "US": {"alpha3": "USA", "numeric": "840", "continent": "North America", "region": "Northern America", "capital": "Washington, D.C.", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".us", "is_eu": False, "is_eea": False, "timezone": "America/New_York"},
    "UY": {"alpha3": "URY", "numeric": "858", "continent": "South America", "region": "South America", "capital": "Montevideo", "currency_code": "UYU", "currency_name": "Uruguayan Peso", "currency_symbol": "$U", "languages": ["es"], "tld": ".uy", "is_eu": False, "is_eea": False, "timezone": "America/Montevideo"},
    "UZ": {"alpha3": "UZB", "numeric": "860", "continent": "Asia", "region": "Central Asia", "capital": "Tashkent", "currency_code": "UZS", "currency_name": "Uzbekistan Som", "currency_symbol": "лв", "languages": ["uz", "ru"], "tld": ".uz", "is_eu": False, "is_eea": False, "timezone": "Asia/Tashkent"},
    "VA": {"alpha3": "VAT", "numeric": "336", "continent": "Europe", "region": "Southern Europe", "capital": "Vatican City", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["it", "la"], "tld": ".va", "is_eu": False, "is_eea": False, "timezone": "Europe/Vatican"},
    "VC": {"alpha3": "VCT", "numeric": "670", "continent": "North America", "region": "Caribbean", "capital": "Kingstown", "currency_code": "XCD", "currency_name": "East Caribbean Dollar", "currency_symbol": "EC$", "languages": ["en"], "tld": ".vc", "is_eu": False, "is_eea": False, "timezone": "America/St_Vincent"},
    "VE": {"alpha3": "VEN", "numeric": "862", "continent": "South America", "region": "South America", "capital": "Caracas", "currency_code": "VEF", "currency_name": "Venezuelan Bolivar", "currency_symbol": "Bs.F", "languages": ["es"], "tld": ".ve", "is_eu": False, "is_eea": False, "timezone": "America/Caracas"},
    "VG": {"alpha3": "VGB", "numeric": "092", "continent": "North America", "region": "Caribbean", "capital": "Road Town", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".vg", "is_eu": False, "is_eea": False, "timezone": "America/Tortola"},
    "VI": {"alpha3": "VIR", "numeric": "850", "continent": "North America", "region": "Caribbean", "capital": "Charlotte Amalie", "currency_code": "USD", "currency_name": "US Dollar", "currency_symbol": "$", "languages": ["en"], "tld": ".vi", "is_eu": False, "is_eea": False, "timezone": "America/St_Thomas"},
    "VN": {"alpha3": "VNM", "numeric": "704", "continent": "Asia", "region": "South-Eastern Asia", "capital": "Hanoi", "currency_code": "VND", "currency_name": "Vietnamese Dong", "currency_symbol": "₫", "languages": ["vi"], "tld": ".vn", "is_eu": False, "is_eea": False, "timezone": "Asia/Ho_Chi_Minh"},
    "VU": {"alpha3": "VUT", "numeric": "548", "continent": "Oceania", "region": "Melanesia", "capital": "Port Vila", "currency_code": "VUV", "currency_name": "Vanuatu Vatu", "currency_symbol": "Vt", "languages": ["bi", "en", "fr"], "tld": ".vu", "is_eu": False, "is_eea": False, "timezone": "Pacific/Efate"},
    "WF": {"alpha3": "WLF", "numeric": "876", "continent": "Oceania", "region": "Polynesia", "capital": "Mata-Utu", "currency_code": "XPF", "currency_name": "CFP Franc", "currency_symbol": "Fr", "languages": ["fr"], "tld": ".wf", "is_eu": False, "is_eea": False, "timezone": "Pacific/Wallis"},
    "WS": {"alpha3": "WSM", "numeric": "882", "continent": "Oceania", "region": "Polynesia", "capital": "Apia", "currency_code": "WST", "currency_name": "Samoan Tala", "currency_symbol": "T", "languages": ["sm", "en"], "tld": ".ws", "is_eu": False, "is_eea": False, "timezone": "Pacific/Apia"},
    "XK": {"alpha3": "XKX", "numeric": "383", "continent": "Europe", "region": "Southern Europe", "capital": "Pristina", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["sq", "sr"], "tld": ".xk", "is_eu": False, "is_eea": False, "timezone": "Europe/Belgrade"},
    "YE": {"alpha3": "YEM", "numeric": "887", "continent": "Asia", "region": "Western Asia", "capital": "Sana'a", "currency_code": "YER", "currency_name": "Yemeni Rial", "currency_symbol": "﷼", "languages": ["ar"], "tld": ".ye", "is_eu": False, "is_eea": False, "timezone": "Asia/Aden"},
    "YT": {"alpha3": "MYT", "numeric": "175", "continent": "Africa", "region": "Eastern Africa", "capital": "Mamoudzou", "currency_code": "EUR", "currency_name": "Euro", "currency_symbol": "€", "languages": ["fr"], "tld": ".yt", "is_eu": False, "is_eea": False, "timezone": "Indian/Mayotte"},
    "ZA": {"alpha3": "ZAF", "numeric": "710", "continent": "Africa", "region": "Southern Africa", "capital": "Pretoria", "currency_code": "ZAR", "currency_name": "South African Rand", "currency_symbol": "R", "languages": ["zu", "xh", "af", "en"], "tld": ".za", "is_eu": False, "is_eea": False, "timezone": "Africa/Johannesburg"},
    "ZM": {"alpha3": "ZMB", "numeric": "894", "continent": "Africa", "region": "Eastern Africa", "capital": "Lusaka", "currency_code": "ZMW", "currency_name": "Zambian Kwacha", "currency_symbol": "ZK", "languages": ["en"], "tld": ".zm", "is_eu": False, "is_eea": False, "timezone": "Africa/Lusaka"},
    "ZW": {"alpha3": "ZWE", "numeric": "716", "continent": "Africa", "region": "Eastern Africa", "capital": "Harare", "currency_code": "ZWL", "currency_name": "Zimbabwean Dollar", "currency_symbol": "$", "languages": ["en", "sn", "nd"], "tld": ".zw", "is_eu": False, "is_eea": False, "timezone": "Africa/Harare"},
}
# fmt: on
